project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
    - text: "Hands-On Exercise"
      menu:
        - text: "Hands-On Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

