{
  "hash": "01d5e70c8596eb3a8e4b86223320678c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 03A\"\nauthor: \"Bhairavi Vairavelu\"\ndate: \"Oct 21 2024\"\ndate-modified: \"last-modified\"\nexecute:\n  eval: true\n  echo: true\n  message: false\n  freeze: true\n---\n\n\n# **Modelling Geography of Financial Inclusion with Geographically Weighted Methods**\n\n## 1.0 Overview\n\nFinancial inclusion is the availability and equality of opportunities to access financial services. It refers to processes by which individuals and businesses can access appropriate, affordable, and timely financial products and services. These financial products and services include banking, loan, equity, and insurance products. It provides paths to enhance inclusiveness in economic growth by enabling the unbanked population to access the means for savings, investments, and insurance towards improving household income and reducing income inequality.\n\n### 1.1 Tasks\n\nIn this exercise, we will be building an explanatory model to determine factors affecting financial inclusion by using geographical weighted regression methods.\n\n### 1.2 Study Area\n\nWe will be focusing on the FinScope Tanzania 2023 dataset for this exercise, and conduct our analysis at the district level.\n\n### 1.3 Analysis Method\n\nGeographically Weighted Regression (GWR) is the spatial statistical technique that we will use in this exercise. GWR takes non-stationary variables into consideration, and models the local relationships between these independent variables, and an outcome of interest. For this exercise, the dependent variable is xx, and the independent variables are divided into either structural (?) and locational (?).\n\n## 2.0 Data\n\nFor the purpose of this exercise, we will be using two datasets:\n\n-   FinScope Tanzania 2023, which contains individual survey interview data\n\n-   Tanzania geoBoundaries, which is a district level boundary GIS data\n\n## 3.0 Installing and Launching Packages\n\nWe intend to utilize the following R packages in this exercise:\n\n-   **olsrr**, for building OLS and performing diagnostic tests\n\n-   **corrplot**, for multivariate data visualization and analysis\n\n-   **ggpubr**, to customize ggplot2-based plots\n\n-   **sf**, for spatial data handling\n\n-   **spdep**, to create spatial weights matrix objects from polygon\n\n-   **GWmodel**, for calibrating geographically weighted family of models\n\n-   **tmap**, for visualizing geospatial objects\n\n-   **tidyverse**, for attribute data handling,\n\n-   **gtsummary**, to create analytical and summary tables\n\n-   **ggstatsplot**, to create graphics with details from statistical tests included in the plots\n\n-   **sfdep**, for computing spatial weights and autocorrelation statistics\n\nThe code chunk below can be used to install and launch the above-mentioned R packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(olsrr, corrplot, ggpubr, sf, spdep, GWmodel, tmap, tidyverse, gtsummary, ggstatsplot, sfdep)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nalso installing the dependency 'glue'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.2:\n  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/4.2/PACKAGES'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  There are binary versions available but the source versions are later:\n          binary source needs_compilation\nglue       1.7.0  1.8.0              TRUE\ngtsummary  1.7.2  2.0.3             FALSE\n\n  Binaries will be installed\npackage 'glue' successfully unpacked and MD5 sums checked\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: cannot remove prior installation of package 'glue'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in file.copy(savedcopy, lib, recursive = TRUE): problem copying\nC:\\R-4.2.2\\library\\00LOCK\\glue\\libs\\x64\\glue.dll to\nC:\\R-4.2.2\\library\\glue\\libs\\x64\\glue.dll: Permission denied\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: restored 'glue'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe downloaded binary packages are in\n\tC:\\Users\\bhair\\AppData\\Local\\Temp\\Rtmp0eLvFb\\downloaded_packages\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\ninstalling the source package 'gtsummary'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in utils::install.packages(package, ...): installation of package\n'gtsummary' had non-zero exit status\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in p_install(package, character.only = TRUE, ...):\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in library(package, lib.loc = lib.loc, character.only = TRUE,\nlogical.return = TRUE, : there is no package called 'gtsummary'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in pacman::p_load(olsrr, corrplot, ggpubr, sf, spdep, GWmodel, tmap, : Failed to install/load:\ngtsummary\n```\n\n\n:::\n:::\n\n\n## 4.0 Geospatial Data Wrangling\n\n### 4.1 Importing Geospatial Data\n\nThe geospatial data used in this exercise, the Tanzania geoBoundaries district level data, is in ESRI shapefile format.\n\nThe code chunk below imports this shapefile by using st_read() of sf packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngb = st_read(dsn = \"data/geospatial\", layer = \"geoBoundaries-TZA-ADM2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `geoBoundaries-TZA-ADM2' from data source \n  `C:\\byebhai8\\ISSS626-GeospatialAnalytics\\Take-Home_Ex\\Take-Home_Ex03\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 170 features and 5 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 29.58953 ymin: -11.76235 xmax: 40.44473 ymax: -0.983143\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe report above shows that the R object used to contain the imported shapefile is called gb, and it is a simple feature object. The geometry type is multipolygon, and the gb simple feature object does not have any EPSG information. These multipolygon features are used to represent the geographic boundaries, and the GIS data is in WGS84 format. Also, the dataset contains 170 rows and 6 columns.\n\n### 4.2 Updating CRS Information\n\nIt is noted that the correct EPSG code for Tanzania is EPSG: 4210, which can be verified here: LINK HERE\n\nAs such, we will use the code chunk below to update the newly imported gb simple feature data frame with the correct EPSG code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngbTransformed <- st_transform(gb, 4210)\n```\n:::\n\n\nAfter transforming the projection metadata, we can verify the projection of the newly transformed gbTransformed by using st_crs() of sf package. This can be achieved by using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(gbTransformed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:4210 \n  wkt:\nGEOGCRS[\"Arc 1960\",\n    DATUM[\"Arc 1960\",\n        ELLIPSOID[\"Clarke 1880 (RGS)\",6378249.145,293.465,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    USAGE[\n        SCOPE[\"Geodesy.\"],\n        AREA[\"Burundi, Kenya, Rwanda, Tanzania and Uganda.\"],\n        BBOX[-11.75,28.85,4.63,41.91]],\n    ID[\"EPSG\",4210]]\n```\n\n\n:::\n:::\n\n\nNote that the EPSG is indicated as 4210 now. We can now use the st_bbox() of sf package to reveal the extent of gbTransformed, as shown in the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(gbTransformed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       xmin        ymin        xmax        ymax \n 29.5889305 -11.7623492  40.4438581  -0.9804983 \n```\n\n\n:::\n:::\n\n\nxx to elaborate what this st_bbox() does and what it means\n\nTo move this into EDA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(gbTransformed) +\n  tm_polygons()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Ex03A_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nx\n\n## 5.0 Aspatial Data Wrangling\n\n### 5.1 Importing Aspatial Data\n\nThe code chunk below uses read_csv() of readr package to import the csv file into R as a tibble data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntz = read_csv(\"data/aspatial/FinScope Tanzania 2023_Individual Main Data_FINAL.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 9915 Columns: 721\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (703): reg_name, dist_name, ward_code1, ward_name, ea_code, clustertype,...\ndbl  (13): SN, reg_code, dist_code, c8c, D6_1_1, D6_1_2, D6_1_3, gov_3, cmg4...\nlgl   (5): e_5_1, e_5_2, g_5_2__5, g_5_2__13, serv2_4\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\nThe report above shows that the R object used to contain the imported attribute data is called tz, and it is a tibble data frame. Also, the dataset contains 9915 rows and 721 columns.\n\nAfter importing the file, it is important for us to examine if the file has been imported correctly. To do this, we will use glimpse() to display the data structure of tz.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(tz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 9,915\nColumns: 721\n$ SN                     <dbl> 4529, 4245, 8149, 6763, 7805, 8232, 9411, 7077,…\n$ reg_name               <chr> \"Mwanza\", \"Kagera\", \"Mbeya\", \"Dodoma\", \"Dar es …\n$ reg_code               <dbl> 19, 18, 12, 1, 7, 13, 25, 4, 25, 1, 19, 13, 25,…\n$ dist_code              <dbl> 7, 7, 3, 3, 2, 1, 3, 6, 5, 3, 5, 4, 3, 2, 7, 4,…\n$ dist_name              <chr> \"Misungwi\", \"Missenyi\", \"Kyela\", \"Kongwa\", \"Ila…\n$ ward_code1             <chr> \"251\", \"011\", \"283\", \"123\", \"252\", \"053\", \"123\"…\n$ ward_name              <chr> \"Mondo\", \"Kakunyu\", \"Nkuyu\", \"Kibaigwa\", \"Majoh…\n$ ea_code                <chr> \"004\", \"001\", \"301\", \"301\", \"029\", \"301\", \"301\"…\n$ clustertype            <chr> \"Rural\", \"Rural\", \"Urban\", \"Urban\", \"Urban\", \"U…\n$ c1                     <chr> \"Original\", \"Original\", \"Original\", \"Original\",…\n$ c2                     <chr> \"Respondent is hhh\", \"Respondent is hhh\", \"Resp…\n$ c7                     <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"Spouse/partner…\n$ c8c                    <dbl> 47, 63, 74, 29, 53, 39, 24, 55, 45, 56, 51, 36,…\n$ c9                     <chr> \"Female\", \"Female\", \"Male\", \"Female\", \"Male\", \"…\n$ c10                    <chr> \"Married/living together\", \"Widowed\", \"Widowed\"…\n$ c11                    <chr> \"Some primary\", \"No formal education\", \"Some pr…\n$ c8n_a1                 <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ c8n_a2                 <chr> \"Some difficulty\", NA, NA, NA, NA, NA, NA, NA, …\n$ c8n_b1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c8n_b2                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c8n_c1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c8n_c2                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c8n_d1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c8n_d2                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c8n_e1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c8n_e2                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c8n_f1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c8n_f2                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c12_1                  <chr> \"You personally own the land/plot where you liv…\n$ c12_2                  <chr> \"No\", \"Yes\", \"Yes\", NA, \"Yes\", \"No\", NA, \"No\", …\n$ c12_3                  <chr> NA, \"Selling agreement/receipt\", \"Letter from l…\n$ c12_4                  <chr> \"Inherited money/the land\", \"Own income\", \"Own …\n$ c22                    <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"No\", \"Y…\n$ c14                    <chr> \"Yes\", \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", …\n$ c15                    <chr> \"You own the land you use for farming\", \"You ow…\n$ C16                    <chr> \"2\", \"0.5\", NA, NA, \"2.5\", \"2\", \"1\", \"4\", \"3\", …\n$ c16_unit               <chr> \"Hectares\", \"Acres\", NA, NA, \"Acres\", \"Acres\", …\n$ c17_1__1               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ c17_1__2               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"Ye…\n$ c17_1__3               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"Yes\", \"No\", \"Yes\", …\n$ c17_1__4               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"N…\n$ c17_1__5               <chr> \"Yes\", \"Yes\", NA, NA, \"No\", \"Yes\", \"Yes\", \"Yes\"…\n$ c17_1__6               <chr> \"No\", \"Yes\", NA, NA, \"No\", \"No\", \"No\", \"Yes\", \"…\n$ c17_1__7               <chr> \"No\", \"No\", NA, NA, \"No\", \"Yes\", \"No\", \"No\", \"N…\n$ c17_1__8               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ c17_1__9               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ c17_1__10              <chr> \"No\", \"No\", NA, NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\",…\n$ c17_1__11              <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ c18_1__1               <chr> \"No\", \"Yes\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"N…\n$ c18_1__2               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"Yes\", \"No\", \"N…\n$ c18_1__3               <chr> \"No\", \"No\", NA, NA, \"No\", \"Yes\", \"Yes\", \"No\", \"…\n$ c18_1__4               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"Yes\", \"No\", \"Yes\", …\n$ c18_1__5               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"Yes\", \"No\", \"No\", \"…\n$ c18_1__6               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"N…\n$ c18_1__7               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ c18_1__8               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"Yes\", \"No\", \"No\", \"…\n$ c18_1__9               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ c18_1__10              <chr> \"Yes\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"No\", \"N…\n$ c18_1__11              <chr> \"No\", \"No\", NA, NA, \"Yes\", \"No\", \"No\", \"No\", \"N…\n$ c18_1__12              <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"Yes\", \"N…\n$ c18_2                  <chr> \"Your household sells some of its crops and use…\n$ c19                    <chr> \"Equally for consumption and selling\", \"Equally…\n$ c20_1                  <chr> \"Yes\", \"Yes\", NA, NA, \"No\", \"No\", \"Yes\", \"Yes\",…\n$ c20_2                  <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\", \"Yes\", \"N…\n$ c23__1                 <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\",…\n$ c23__2                 <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Ye…\n$ c23__3                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c24_2                  <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\",…\n$ c24_2a                 <chr> \"Yes\", NA, \"Yes\", \"No\", \"Yes\", \"No\", \"No\", \"Yes…\n$ C24_3                  <chr> \"It is bad – calls rarely connect, calls often …\n$ c24_1                  <chr> \"Yes\", \"2\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", …\n$ c25__1                 <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ c25__2                 <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ c25X1__1               <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ c25X1__3               <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ c25X1__4               <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", …\n$ c25X1__5               <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ c25X1__6               <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ c25X2__1               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c25X2__2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c25X2__3               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c25X2__4               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c25X2__5               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c25X2__6               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ c26                    <chr> NA, \"Don’t have enough money/expensive to buy t…\n$ c27__1                 <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Ye…\n$ c27__2                 <chr> \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"No\", \"No\", \"No…\n$ c27__3                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__4                 <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\"…\n$ c27__5                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__6                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__7                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__8                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__9                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__10                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__11                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__12                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__13                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__14                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__15                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__16                <chr> \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ c27__18                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__19                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__20                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ c27__17                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D_1                    <chr> \"Medical expenses\", \"Medical expenses\", \"Farmin…\n$ D2_1__1                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__2                <chr> \"Yes\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"No\", …\n$ D2_1__3                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__4                <chr> \"Yes\", \"No\", \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\", \"…\n$ D2_1__5                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__6                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__7                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__8                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__9                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\"…\n$ D2_1__10               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__11               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_1__12               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ D2_4                   <chr> \"Make own Money from trading/selling :Anything …\n$ D3_1                   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ D3_2                   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ D4                     <chr> \"Crops/produce I grow\", \"Crops/produce I grow\",…\n$ D5                     <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ D5a                    <chr> \"Specific premises with a unique address\", \"Spe…\n$ D5b                    <chr> \"From Inheritance\", \"Gift from family/friends\",…\n$ D6_1_1                 <dbl> 0, 0, NA, 2, 0, 0, NA, 5, 0, 0, 0, 0, 0, NA, 0,…\n$ D6_1_2                 <dbl> NA, NA, NA, 2, NA, NA, NA, 0, NA, NA, NA, NA, N…\n$ D6_1_3                 <dbl> NA, NA, NA, 0, NA, NA, NA, 5, NA, NA, NA, NA, N…\n$ D6_2                   <chr> NA, NA, NA, \"Salaries/wages\", NA, NA, NA, \"Sala…\n$ D6_3                   <chr> \"Middlemen/traders\", \"Neighbors/public\", NA, \"N…\n$ D6_3a__1               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", \"No…\n$ D6_3a__2               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", \"No…\n$ D6_3a__3               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", \"Ye…\n$ D6_3a__4               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"Yes\", \"N…\n$ D6_3a__5               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", \"No…\n$ D6_3a__6               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", \"No…\n$ D6_3a__7               <chr> \"No\", \"No\", NA, \"Yes\", \"No\", \"No\", NA, \"No\", \"N…\n$ D6_3a__8               <chr> \"No\", \"No\", NA, \"No\", \"No\", \"No\", NA, \"Yes\", \"N…\n$ D6_4                   <chr> \"Crop pests/disease\", \"Lack of rainfall/climate…\n$ D6_4a                  <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4b                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ D6_4c__1               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__2               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__3               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__4               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__5               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__6               <chr> \"No\", \"Yes\", NA, NA, \"Yes\", \"Yes\", NA, \"Yes\", \"…\n$ D6_4c__7               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__8               <chr> \"Yes\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\"…\n$ D6_4c__9               <chr> \"No\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\",…\n$ D6_4c__10              <chr> \"Yes\", \"No\", NA, NA, \"No\", \"No\", NA, \"No\", \"No\"…\n$ D7                     <chr> NA, NA, NA, NA, NA, NA, NA, \"Household member (…\n$ D7a                    <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"Yes…\n$ D7b                    <chr> \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ D7c                    <chr> NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ D7d                    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ e_1_1                  <chr> \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\", …\n$ e_1_1new               <chr> \"You control how all your money is spent\", \"You…\n$ e_2                    <chr> \"Respondent is involved\", \"Respondent is involv…\n$ e_3_3__1               <chr> \"Yes\", \"Yes\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"…\n$ e_3_3__2               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\"…\n$ e_3_3__3               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__4               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__5               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__6               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__7               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__8               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__9               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__11              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__12              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__13              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__14              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__15              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_3_3__16              <chr> \"No\", \"No\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"No\", \"Y…\n$ e_4                    <chr> \"No, I don’t agree\", \"No, I don’t agree\", \"No, …\n$ e_4n                   <chr> \"Do not do this\", \"Do not do this\", \"Not that a…\n$ e_5_1                  <lgl> FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TR…\n$ e_5_2                  <lgl> FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE,…\n$ e_5_n_1                <chr> \"Selling or pawning assets\", \"Gift from friends…\n$ e_5_n_2                <chr> \"Not very possible\", \"Not at all possible\", \"So…\n$ e_6                    <chr> \"Sell possessions (e.g., crops, livestock, jewe…\n$ e_7                    <chr> \"often\", \"often\", \"always\", \"often\", \"always\", …\n$ e_7_n_1__1             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_7_n_1__2             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_7_n_1__3             <chr> \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\"…\n$ e_7_n_1__4             <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"Yes\", \"N…\n$ e_7_n_1__5             <chr> \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Y…\n$ e_7_n_1__6             <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No…\n$ e_7_n_1__7             <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ e_7_n_1__8             <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"No\", \"…\n$ e_7_n_1__9             <chr> \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ e_7_n_1__10            <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\"…\n$ e_7_n_2                <chr> \"Sold livestock\", \"Got assistance from friends,…\n$ e_7_n_3                <chr> \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", …\n$ e_7_n_4                <chr> \"Worse\", \"Better\", \"Worse\", \"Worse\", \"Worse\", \"…\n$ e_10                   <chr> \"Don’t know/Have no plans/Have not yet thought …\n$ e_11_1                 <chr> \"House\", \"Land/farm\", \"Land/farm\", \"House\", \"Ho…\n$ e_11_2                 <chr> \"Engaged in farming activities to make extra mo…\n$ e_11_2_n_1             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ e_11_2_n_2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ e_11_2_n_3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ e_12_1                 <chr> \"Agree\", \"Agree\", \"Agree\", \"Agree\", \"Agree\", \"A…\n$ e_12_2                 <chr> \"Disagree\", \"Disagree\", \"Disagree\", \"Disagree\",…\n$ e_12_4                 <chr> \"Agree\", \"Disagree\", \"Agree\", \"Agree\", \"Agree\",…\n$ e_13                   <chr> \"The family members/relatives or friends\", \"The…\n$ E14_1__1               <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No…\n$ E14_1__2               <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"N…\n$ E14_1__3               <chr> \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\"…\n$ E14_1__4               <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ E14_1__5               <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\"…\n$ E14_1__6               <chr> \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No…\n$ f_2                    <chr> \"No\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"Yes\", \"…\n$ f_3_1_1                <chr> \"Disagree\", \"Agree\", \"Disagree\", \"Agree\", \"Disa…\n$ f_3_1_2                <chr> \"Disagree\", \"Disagree\", \"Disagree\", \"Agree\", \"D…\n$ f_3_2_1__1             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"Yes…\n$ f_3_2_1__2             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"Yes…\n$ f_3_2_1__3             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ f_3_2_1__4             <chr> \"Yes\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"Y…\n$ f_3_2_1__5             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ f_3_2_1__6             <chr> \"No\", \"Yes\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No…\n$ f_3_2_1__7             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\"…\n$ f_3_2_1__8             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ f_3_2_1__9             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\"…\n$ f_3_2_2                <chr> \"Mobile money operators i.e. in a wallet on you…\n$ F4_1__1                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__2                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__3                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__4                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__5                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__6                <chr> NA, \"No\", \"Yes\", \"No\", NA, NA, \"Yes\", \"Yes\", \"N…\n$ F4_1__7                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__8                <chr> NA, \"Yes\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\"…\n$ F4_1__9                <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__10               <chr> NA, \"No\", \"No\", \"Yes\", NA, NA, \"Yes\", \"Yes\", \"Y…\n$ F4_1__11               <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__12               <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__13               <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_1__14               <chr> NA, \"No\", \"No\", \"No\", NA, NA, \"No\", \"No\", \"No\",…\n$ F4_4                   <chr> NA, \"Save with savings group\", \"Your normal mob…\n$ F4_5                   <chr> NA, \"It is the safest\", \"Quickest access to sav…\n$ f_5                    <chr> NA, \"An emergency other than medical\", \"An emer…\n$ f_5_n_1__1             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"No…\n$ f_5_n_1__2             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"Ye…\n$ f_5_n_1__3             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\"…\n$ f_5_n_1__4             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"No…\n$ f_5_n_1__5             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"Ye…\n$ f_5_n_2__1             <chr> NA, NA, NA, NA, \"No\", NA, \"No\", NA, NA, \"No\", \"…\n$ f_5_n_2__2             <chr> NA, NA, NA, NA, \"No\", NA, \"No\", \"No\", NA, \"No\",…\n$ f_5_n_2__3             <chr> NA, NA, NA, NA, \"No\", NA, NA, NA, NA, \"No\", NA,…\n$ f_5_n_2__4             <chr> NA, NA, NA, NA, \"No\", NA, \"No\", NA, NA, \"No\", \"…\n$ f_5_n_2__5             <chr> NA, NA, NA, NA, \"No\", NA, \"No\", \"No\", \"No\", \"Ye…\n$ f_7_1                  <chr> \"No\", \"No\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"No\", \"N…\n$ f_7_2                  <chr> NA, NA, \"Bought livestock\", \"Bought/started a b…\n$ f_8_1                  <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ f_8_2                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"Bo…\n$ f_9                    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_1_1_1                <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\"…\n$ g_1_1_4                <chr> \"Yes\", \"Don't know (DK)\", \"No\", \"Yes\", \"No\", \"N…\n$ g_1_1_7                <chr> \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ g_1_1_8                <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"…\n$ g_1_2_1__1             <chr> \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\"…\n$ g_1_2_1__2             <chr> \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\"…\n$ g_1_2_1__3             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ g_1_2_1__4             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ g_1_2_1__5             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\"…\n$ g_1_2_1__6             <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"…\n$ g_1_2_1__7             <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No…\n$ g_1_2_1__8             <chr> \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"…\n$ g_1_2_1__9             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ g_1_2_1__10            <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\"…\n$ g_1_2_2                <chr> \"Savings groups / Community Microfinance groups…\n$ g_2_1_1                <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", …\n$ g_2_1_2                <chr> \"Yes\", NA, \"Yes\", \"No\", \"No\", NA, \"Yes\", NA, \"Y…\n$ g_2_2                  <chr> \"In the past 90 days\", NA, \"In the past 90 days…\n$ g_2_3                  <chr> \"60000\", NA, \"100000\", \"200000\", \"90000\", NA, \"…\n$ g_2_4                  <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"N…\n$ g_2_5                  <chr> \"No\", NA, \"Yes\", \"Yes\", \"Yes\", NA, \"No\", NA, \"N…\n$ g_2_6                  <chr> NA, NA, \"100000\", \"60000\", \"90000\", NA, NA, NA,…\n$ g_2_6n                 <chr> NA, NA, \"Have a bit more debt than is manageabl…\n$ g_4                    <chr> NA, \"Do not know where to borrow money from\", N…\n$ g_5_1__1               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__2               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__3               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__5               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__6               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__7               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__8               <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"Yes\", NA, \"No\"…\n$ g_5_1__9               <chr> \"Yes\", NA, \"No\", \"No\", \"Yes\", NA, \"Yes\", NA, \"Y…\n$ g_5_1__10              <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__11              <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"No\", NA, \"No\", NA, \"N…\n$ g_5_1__12              <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__13              <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_1__14              <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_5_2__1               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__3               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__5               <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__6               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__7               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__8               <chr> NA, NA, NA, NA, NA, NA, \"Yes\", NA, NA, NA, NA, …\n$ g_5_2__9               <chr> \"Yes\", NA, NA, NA, \"Yes\", NA, \"Yes\", NA, \"Yes\",…\n$ g_5_2__10              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__11              <chr> \"Yes\", NA, \"Yes\", \"Yes\", NA, NA, NA, NA, NA, \"Y…\n$ g_5_2__12              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__13              <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_2__14              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_5_3                  <chr> \"Savings group\", NA, \"Savings group\", NA, \"Fami…\n$ g_6                    <chr> \"Quickest access to the money\", NA, \"Quickest a…\n$ g_7                    <chr> \"No\", NA, \"Yes\", \"Yes\", \"No\", NA, \"No\", NA, \"No…\n$ g_8_1                  <chr> \"T-Bills, T-Bonds or shares purchase\", NA, \"An …\n$ g_8_2                  <chr> \"Same day\", NA, \"Same day\", \"Less than a week\",…\n$ g_9                    <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_12_1                 <chr> \"No\", NA, \"No\", \"No\", \"No\", NA, \"No\", NA, \"No\",…\n$ g_12_2                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ g_13_1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ pay_1                  <chr> \"Disagree\", \"Disagree\", \"Disagree\", \"Agree\", \"D…\n$ pay_1_4                <chr> \"Disagree\", \"Agree\", \"Agree\", \"Agree\", \"Agree\",…\n$ pay_1_5                <chr> \"Disagree\", \"Agree\", \"Disagree\", \"Agree\", \"Agre…\n$ pay_1_6                <chr> \"A mobile money access point\", \"Own hidding pla…\n$ pay_1_7                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"Yes…\n$ pay_1_8                <chr> \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"No\", \"Yes\", \"Y…\n$ pay2_1__1              <chr> NA, NA, \"No\", NA, \"No\", NA, \"Yes\", \"No\", NA, NA…\n$ pay2_1__2              <chr> NA, NA, \"Yes\", NA, \"No\", NA, \"No\", \"No\", NA, NA…\n$ pay2_1__3              <chr> NA, NA, \"No\", NA, \"Yes\", NA, \"Yes\", \"No\", NA, N…\n$ pay2_1__4              <chr> NA, NA, \"No\", NA, \"No\", NA, \"No\", \"Yes\", NA, NA…\n$ pay2_1__5              <chr> NA, NA, \"No\", NA, \"No\", NA, \"Yes\", \"No\", NA, NA…\n$ pay2_1__6              <chr> NA, NA, \"No\", NA, \"No\", NA, \"No\", \"No\", NA, NA,…\n$ pay2_1__7              <chr> NA, NA, \"No\", NA, \"No\", NA, \"No\", \"Yes\", NA, NA…\n$ pay3_1                 <chr> NA, NA, \"In the past 30 days\", NA, \"In the past…\n$ pay4_1                 <chr> \"Yes\", \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", …\n$ pay5_1__1              <chr> \"No\", NA, \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ pay5_1__2              <chr> \"Yes\", NA, \"Yes\", NA, \"No\", \"Yes\", \"No\", \"Yes\",…\n$ pay5_1__3              <chr> \"No\", NA, \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ pay5_1__4              <chr> \"No\", NA, \"No\", NA, \"Yes\", \"No\", \"Yes\", \"No\", \"…\n$ pay5_1__5              <chr> \"No\", NA, \"No\", NA, \"No\", \"No\", \"Yes\", \"No\", \"N…\n$ pay5_1__6              <chr> \"No\", NA, \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ pay5_1__7              <chr> \"No\", NA, \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No…\n$ pay6_1                 <chr> \"In the past 90 days\", NA, \"In the past 6 month…\n$ pb1                    <chr> \"By using cash\", \"By using cash\", \"By using cas…\n$ pb2                    <chr> \"You don’t buy this because you never use this/…\n$ pb3                    <chr> \"By using cash\", \"By using cash\", \"By using cas…\n$ pb4                    <chr> \"You don’t buy this because you never use this/…\n$ pb5                    <chr> \"By using cash\", \"You don’t buy this because yo…\n$ pb2_1                  <chr> \"Never\", \"Weekly\", \"Monthly\", \"Daily\", \"Daily\",…\n$ pb2_2                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb2_3                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb2_4                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb2_5                  <chr> \"Never\", \"Never\", \"Never\", \"Less often than mon…\n$ pb2_6                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb3_1                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb3_2                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb3_3                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb3_4                  <chr> \"Never\", \"Never\", \"Never\", \"Never\", \"Never\", \"N…\n$ pb4_1                  <chr> \"N/A / Do not do\", \"N/A / Do not do\", \"Less\", \"…\n$ pb4_2                  <chr> \"N/A / Do not do\", \"N/A / Do not do\", \"N/A / Do…\n$ pb4_3                  <chr> \"N/A / Do not do\", \"N/A / Do not do\", \"Less\", \"…\n$ pb4_4                  <chr> \"Less\", \"N/A / Do not do\", \"Less\", \"The same\", …\n$ pb4_5                  <chr> \"N/A / Do not do\", \"N/A / Do not do\", \"Less\", \"…\n$ pb4_6                  <chr> \"N/A / Do not do\", \"N/A / Do not do\", \"N/A / Do…\n$ pb4_7                  <chr> \"N/A / Do not do\", \"N/A / Do not do\", \"N/A / Do…\n$ gov_1__1               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_1__2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_1__3               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_1__4               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__1               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__3               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__4               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__5               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__6               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_2__7               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ gov_3                  <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ bill_1                 <chr> \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"No…\n$ bill2_1                <chr> NA, NA, \"Monthly\", NA, NA, NA, \"Never\", NA, NA,…\n$ bill2_2                <chr> NA, NA, \"Never\", NA, NA, NA, \"Never\", NA, NA, \"…\n$ bill2_3                <chr> NA, NA, \"Never\", NA, NA, NA, \"Never\", NA, NA, \"…\n$ bill2_4                <chr> NA, NA, \"Never\", NA, NA, NA, \"Never\", NA, NA, \"…\n$ bill2_5                <chr> NA, NA, \"Never\", NA, NA, NA, \"Monthly\", NA, NA,…\n$ serv1_1__1             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__2             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__3             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__4             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__5             <chr> \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ serv1_1__6             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__7             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__8             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__9             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__10            <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"No\", \"…\n$ serv1_1__11            <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ serv1_1__12            <chr> \"No\", \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\"…\n$ serv1_2                <chr> \"Savings group Community microfinance groups (C…\n$ serv1_3                <chr> \"I can get a loan when I need it\", \"I can turn …\n$ serv1_5                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv1_6                <chr> \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"…\n$ serv1_7__1             <chr> \"No\", NA, NA, NA, NA, \"Yes\", \"No\", NA, \"No\", NA…\n$ serv1_7__2             <chr> \"No\", NA, NA, NA, NA, \"Yes\", \"Yes\", NA, \"Yes\", …\n$ serv1_7__3             <chr> \"No\", NA, NA, NA, NA, \"No\", \"No\", NA, \"No\", NA,…\n$ serv1_7__4             <chr> \"Yes\", NA, NA, NA, NA, \"No\", \"No\", NA, \"No\", NA…\n$ serv1_8                <chr> NA, \"The issue was not reported\", \"Yes\", \"Yes\",…\n$ serv3_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv5_0                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv5_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_1__1             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_1__2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_1__3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_1__4             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_1__5             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_3                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ serv2_4                <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm3_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm4_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm6_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm6_3                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm6_3a               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm7_1__1             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm7_1__2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm7_1__3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm7_1__4             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm7_1__5             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm7_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__1             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__4             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__5             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__6             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1__7             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1a__1            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1a__3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1a__4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1a__5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm8_1a__6            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm9_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ comm10_1               <chr> \"Banks are too far away\", \"Banks are too far aw…\n$ micro5_1               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro1_1               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_1__1            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_1__2            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_1__3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_1__4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_3               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_4               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro2_5               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro4_0               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro6_2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro6_3               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro7_1__1            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro7_1__2            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro7_1__3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro7_1__4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro7_1__5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro7_2               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro8_0__1            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro8_0__2            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro8_0__3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro8_0__4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro8_0__5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro8_0__6            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro9_0               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro9_0a__1           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro9_0a__2           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro9_0a__3           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro9_0a__4           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro9_0a__6           <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ micro10_0              <chr> \"Don’t know them\", \"Too far away\", \"Cannot main…\n$ cred1_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred1_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred2_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__1             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__4             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__5             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__6             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__7             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1__8             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1a__1            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1a__2            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1a__3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1a__4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1a__5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_1a__6            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__1             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__4             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__5             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__6             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__7             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__8             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred3_2__9             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred4_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred4_3                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred5_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred5_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred6_1                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred6_2                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cred9_0                <chr> \"Don’t know SACCOs\", \"Too far away\", \"Don’t hav…\n$ pens1                  <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ pens2                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ pens3                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ pens4                  <chr> \"Don’t know what pensions are\", \"Don’t know wha…\n$ ins1_1                 <chr> \"Not every month but more than once or twice in…\n$ ins1_2                 <chr> \"Private health care facility /consult private …\n$ ins1_3__1              <chr> \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"No\", \"N…\n$ ins1_3__2              <chr> \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"…\n$ ins1_3__3              <chr> \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", …\n$ ins1_3__4              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ ins2                   <chr> \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ ins3_1__1              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__2              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__3              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__4              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__5              <chr> NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, NA, …\n$ ins3_1__6              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__7              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__8              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__9              <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__10             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__11             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__12             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__13             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__14             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__15             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__16             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__17             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_1__18             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins3_5                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ ins4_1                 <chr> NA, NA, \"To make sure my family has money to co…\n$ ins4_2                 <chr> NA, NA, \"Lack of medicine / poor service at hos…\n$ ins4_2a__1             <chr> NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, NA, …\n$ ins4_2a__2             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins4_2a__3             <chr> NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, NA, …\n$ ins4_2a__4             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins4_2a__5             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins4_2a__6             <chr> NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, NA, N…\n$ ins5                   <chr> NA, NA, \"In the past 6 months\", NA, NA, NA, NA,…\n$ ins6_1                 <chr> \"Does not know the benefits of health insurance…\n$ ins6_2                 <chr> \"Does not know the benefits of insurance\", \"Doe…\n$ ins6_2a__1             <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\",…\n$ ins6_2a__2             <chr> \"No\", \"Yes\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\"…\n$ ins6_2a__3             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ ins6_2a__4             <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ mob1_3                 <chr> \"Agree\", \"Disagree\", \"Agree\", \"Agree\", \"Disagre…\n$ mob1_4                 <chr> \"Disagree\", \"Agree\", \"Disagree\", \"Disagree\", \"A…\n$ mob1_6                 <chr> \"Disagree\", \"Disagree\", \"Disagree\", \"Disagree\",…\n$ mob1_7                 <chr> \"Disagree\", \"Disagree\", \"Disagree\", \"Disagree\",…\n$ mob1_8                 <chr> \"Disagree\", \"Disagree\", \"Dont know\", \"Disagree\"…\n$ mob1_9                 <chr> \"Agree\", \"Agree\", \"Disagree\", \"Disagree\", \"Agre…\n$ mob1_10                <chr> \"Agree\", \"Disagree\", \"Agree\", \"Agree\", \"Agree\",…\n$ mob2                   <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\",…\n$ mob3                   <chr> NA, \"I do not have a smartphone\", NA, NA, NA, N…\n$ mob4                   <chr> \"5 years ago or more\", NA, \"5 years ago or more…\n$ mob5                   <chr> \"I had to receive money from another person\", N…\n$ mob5a                  <chr> \"Agree\", NA, \"Agree\", \"Agree\", \"Agree\", \"Agree\"…\n$ mob5b                  <chr> \"Agree\", NA, \"Agree\", \"Agree\", \"Agree\", \"Agree\"…\n$ mob5c                  <chr> \"Agree\", NA, \"Agree\", \"Disagree\", \"Agree\", \"Dis…\n$ mob5d                  <chr> \"Agree\", NA, \"Agree\", \"Agree\", \"Agree\", \"Agree\"…\n$ mob5e                  <chr> \"Agree\", NA, \"Disagree\", \"Agree\", \"Disagree\", \"…\n$ mob5f                  <chr> \"Agree\", NA, \"Agree\", \"Agree\", \"Agree\", \"Agree\"…\n$ mob5g                  <chr> \"Disagree\", NA, \"Disagree\", \"Disagree\", \"Disagr…\n$ mob6                   <chr> \"You are registered to use mobile money\", NA, \"…\n$ mob7                   <chr> NA, NA, NA, \"I do not have a state ID, National…\n$ mob8__1                <chr> \"Yes\", NA, \"Yes\", \"No\", \"No\", \"No\", \"Yes\", \"No\"…\n$ mob8__2                <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", …\n$ mob8__3                <chr> \"No\", NA, \"No\", \"Yes\", \"No\", \"Yes\", \"No\", \"No\",…\n$ mob8__4                <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob8__5                <chr> \"Yes\", NA, \"Yes\", \"No\", \"Yes\", \"No\", \"No\", \"No\"…\n$ mob8__6                <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob9_2                 <chr> \"In the past 90 days\", NA, \"In the past 90 days…\n$ mob9_3                 <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"On…\n$ mob10_1__1             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"Yes\", \"Yes\",…\n$ mob10_1__2             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob10_1__3             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"Yes\", \"Yes\",…\n$ mob10_1__4             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob10_1__5             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob10_1__6             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob10_1__7             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob10_2__1             <chr> NA, NA, NA, NA, NA, NA, \"No\", \"No\", NA, \"No\", N…\n$ mob10_2__2             <chr> NA, NA, NA, NA, NA, NA, \"No\", \"No\", NA, \"No\", N…\n$ mob10_2__3             <chr> NA, NA, NA, NA, NA, NA, \"Yes\", \"Yes\", NA, \"Yes\"…\n$ mob10_2__4             <chr> NA, NA, NA, NA, NA, NA, \"No\", \"No\", NA, \"No\", N…\n$ mob11_1                <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob11_2__1             <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"No\", NA, NA, N…\n$ mob11_2__2             <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"No\", NA, NA, N…\n$ mob11_2__3             <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"No\", NA, NA, N…\n$ mob11_3                <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"Ask family/fri…\n$ mob12                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"Once or twice …\n$ mob13                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, \"1000\", NA, NA,…\n$ mob14                  <chr> \"Easy to use\", NA, \"Quick to use\", \"Easy to use…\n$ mob15                  <chr> \"Network failures\", NA, \"It is expensive\", \"Not…\n$ mob16_1                <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ mob16_2__1             <chr> \"No\", NA, \"No\", \"Yes\", \"No\", \"No\", \"No\", \"Yes\",…\n$ mob16_2__2             <chr> \"No\", NA, \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"Ye…\n$ mob16_2__3             <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"…\n$ mob16_2__4             <chr> \"No\", NA, \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"No\",…\n$ mob16_2__5             <chr> \"No\", NA, \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\"…\n$ mob16_2__6             <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"Y…\n$ mob16_2__7             <chr> \"No\", NA, \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Y…\n$ mob16_2__8             <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob17                  <chr> \"Longer than 6 months ago\", NA, \"In the past 90…\n$ mob17a__1              <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob17a__2              <chr> \"Yes\", NA, \"Yes\", \"Yes\", \"Yes\", \"No\", \"Yes\", \"Y…\n$ mob17a__3              <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob17a__4              <chr> \"No\", NA, \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ mob17a__5              <chr> \"No\", NA, \"No\", \"Yes\", \"No\", \"No\", \"Yes\", \"Yes\"…\n$ mob17a__6              <chr> \"No\", NA, \"No\", \"No\", \"Yes\", \"No\", \"No\", \"No\", …\n$ mob17a__7              <chr> \"No\", NA, \"No\", \"No\", \"Yes\", \"Yes\", \"Yes\", \"Yes…\n$ mob17b                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ mob17c                 <chr> NA, NA, NA, NA, \"0\", NA, NA, NA, NA, NA, NA, NA…\n$ mob17d                 <chr> NA, NA, NA, NA, \"Occasionally when I get cash o…\n$ mob17e                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ mob17f__1              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ mob17f__2              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ mob17f__3              <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ mob17f__4              <chr> \"No\", \"No\", \"Yes\", \"No\", \"Yes\", \"Yes\", \"No\", \"N…\n$ cmg1__1                <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg1__2                <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg1__3                <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"Ye…\n$ cmg1__4                <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg1a                  <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg2                   <chr> \"To borrow money\", \"Can get access to money in …\n$ cmg3                   <chr> \"5 years ago or more\", \"5 years ago or more\", \"…\n$ cmg4_1__1              <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_1__2              <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_1__3              <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA, …\n$ cmg4_1__4              <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_1__5              <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_1__6              <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_1__7              <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_2__1              <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_2__2              <chr> \"Yes\", \"Yes\", \"No\", \"Yes\", NA, NA, NA, NA, NA, …\n$ cmg4_2__3              <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_2__4              <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_2__5              <chr> \"No\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA, …\n$ cmg4_2__6              <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_2__7              <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_2__8              <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_2__9              <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_2__10             <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_2a__1             <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_2a__2             <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_2a__3             <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_2a__4             <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA, …\n$ cmg4_2a__5             <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA, …\n$ cmg4_2a__6             <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA,…\n$ cmg4_2a__7             <chr> \"Yes\", \"No\", \"Yes\", \"No\", NA, NA, NA, NA, NA, \"…\n$ cmg4_3                 <dbl> 2, 2, 3, 1, NA, NA, NA, NA, NA, 1, NA, NA, NA, …\n$ cmg4_4                 <chr> \"0\", \"2\", \"1\", NA, NA, NA, NA, NA, NA, NA, NA, …\n$ cmg4_7                 <chr> \"Once a month\", \"Once a month\", \"Once a month\",…\n$ cmg4_8                 <dbl> 12000, 1000, 5000, 2500, NA, NA, NA, NA, NA, 12…\n$ cmg4_9                 <chr> \"Once or twice a year\", NA, \"Monthly\", \"Once or…\n$ cmg4_10                <chr> \"300000\", NA, \"100000\", \"200000\", NA, NA, NA, N…\n$ cmg4_11                <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, \"Once or tw…\n$ cmg4_12                <chr> \"400000\", \"0\", \"Refused\", \"Can’t remember\", NA,…\n$ cmg4_13__1             <chr> \"No\", \"No\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA, \"…\n$ cmg4_13__2             <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_13__3             <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_13__4             <chr> \"Yes\", \"No\", \"Yes\", \"Yes\", NA, NA, NA, NA, NA, …\n$ cmg4_13__5             <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_13__6             <chr> \"No\", \"No\", \"No\", \"No\", NA, NA, NA, NA, NA, \"No…\n$ cmg4_13__7             <chr> \"No\", \"No\", \"No\", \"Yes\", NA, NA, NA, NA, NA, \"N…\n$ cmg4_13__8             <chr> \"Yes\", \"Yes\", \"No\", \"No\", NA, NA, NA, NA, NA, \"…\n$ cmg4_14                <chr> \"Once a month\", \"Once a month\", \"Once a month\",…\n$ cmg4_14a__1            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__2            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__3            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__4            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__5            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__6            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__7            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__8            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ cmg4_14a__9            <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ lender1                <chr> NA, NA, NA, \"Quick access to money\", NA, NA, NA…\n$ lender3                <chr> NA, NA, NA, \"In the past 90 days\", NA, NA, NA, …\n$ lender4                <dbl> NA, NA, NA, 1e+05, NA, NA, NA, NA, NA, NA, NA, …\n$ lender4a               <chr> NA, NA, NA, \"No\", NA, NA, NA, NA, NA, NA, NA, N…\n$ lender4b__1            <chr> NA, NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, …\n$ lender4b__2            <chr> NA, NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, …\n$ lender4b__3            <chr> NA, NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, …\n$ lender4b__4            <chr> NA, NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, …\n$ lender4b__5            <chr> NA, NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, …\n$ lender4b__6            <chr> NA, NA, NA, \"Yes\", NA, NA, NA, NA, NA, NA, NA, …\n$ lender5                <chr> NA, NA, NA, \"Short repayment terms\", NA, NA, NA…\n$ k_1_1                  <chr> \"Can neither read nor write\", \"Can neither read…\n$ k_1_2                  <chr> \"Can neither read nor write\", \"Can neither read…\n$ k_2_1                  <chr> \"TSH 7 000\", \"Don’t know/refused\", \"TSH 7 000\",…\n$ k_2_2                  <chr> \"Other answer which is wrong\", \"Don’t know/refu…\n$ k_2_3                  <chr> \"Other answer which is wrong\", \"Don’t know/refu…\n$ k_2_4                  <chr> \"Other answer which is wrong\", \"Don’t know/refu…\n$ k_3__1                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ k_3__2                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"Yes\", \"No\"…\n$ k_3__3                 <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\",…\n$ k_3__4                 <chr> \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"Yes\", \"No\",…\n$ RU                     <chr> \"Rural\", \"Rural\", \"Other urban\", \"Other urban\",…\n$ MZ                     <chr> \"Mainland\", \"Mainland\", \"Mainland\", \"Mainland\",…\n$ tot                    <chr> \"national\", \"national\", \"national\", \"national\",…\n$ Household_weight       <dbl> 1381.5372, 2986.4383, 1434.8197, 2352.7250, 180…\n$ population_wt          <dbl> 3191.1104, 3675.4824, 2043.7091, 4003.1678, 261…\n$ MM                     <chr> \"MM\", \"Not MM\", \"MM\", \"MM\", \"MM\", \"MM\", \"MM\", \"…\n$ BANKED                 <chr> \"Not Banked\", \"Not Banked\", \"Not Banked\", \"Not …\n$ MFI                    <chr> \"Not MFI\", \"Not MFI\", \"Not MFI\", \"Not MFI\", \"No…\n$ PENSION                <chr> \"Not PENSION\", \"Not PENSION\", \"Not PENSION\", \"N…\n$ INSURANCE              <chr> \"0\", \"0\", \"INSURANCE\", \"0\", \"0\", \"0\", \"0\", \"0\",…\n$ SACCO                  <chr> \"Not SACCO\", \"Not SACCO\", \"Not SACCO\", \"Not SAC…\n$ CAPITALM_FUND_MANAGERS <chr> \"Not CAPITALM_FUND_MANAGERS\", \"Not CAPITALM_FUN…\n$ FORM_INVESTMENTS       <chr> \"Not FORM_INVESTMENTS\", \"Not FORM_INVESTMENTS\",…\n$ CMG                    <chr> \"CMG\", \"CMG\", \"CMG\", \"CMG\", \"Not CMG\", \"Not CMG…\n$ INFORMAL_MONEYLENDER   <chr> \"Not INFORMAL_MONEYLENDER\", \"Not INFORMAL_MONEY…\n$ SOCIAL_GROUPS          <chr> \"Not SOCIAL_GROUPS\", \"Not SOCIAL_GROUPS\", \"Not …\n$ OTHER_FORMAL           <chr> \"OTHER_FORMAL\", \"OTHER_FORMAL\", \"OTHER_FORMAL\",…\n$ OVERALL_FORMAL         <chr> \"OVERALL_FORMAL\", \"OVERALL_FORMAL\", \"OVERALL_FO…\n$ INFORMAL               <chr> \"INFORMAL incl SACCO AND CMG RISK CONTRIBUTIONS…\n$ fasx                   <chr> \"Other formal non-bank\", \"Other formal non-bank…\n$ overlapx               <chr> \"informal AND formal\", \"informal AND formal\", \"…\n$ IncomeMain             <chr> \"Farmers and fishers\", \"Farmers and fishers\", \"…\n$ BusO                   <chr> \"nor\", \"nor\", \"nor\", \"Business owners\", \"nor\", …\n$ DEDICATED_FARMER       <chr> \"Not Dedicated farmer\", \"Not Dedicated farmer\",…\n$ SMALLHOLDER_FARMER     <chr> \"Not Smallholder farmer\", \"Not Smallholder farm…\n```\n\n\n:::\n:::\n\n\nWe can also use summary() of base R to display the summary statistics of tz tibble data frame:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(tz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       SN         reg_name            reg_code       dist_code   \n Min.   :   1   Length:9915        Min.   : 1.00   Min.   :1.00  \n 1st Qu.:2480   Class :character   1st Qu.: 7.00   1st Qu.:1.00  \n Median :4958   Mode  :character   Median :14.00   Median :3.00  \n Mean   :4958                      Mean   :16.97   Mean   :2.93  \n 3rd Qu.:7436                      3rd Qu.:21.00   3rd Qu.:4.00  \n Max.   :9915                      Max.   :55.00   Max.   :8.00  \n                                                                 \n  dist_name          ward_code1         ward_name           ea_code         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n clustertype             c1                 c2                 c7           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n      c8c              c9                c10                c11           \n Min.   : 16.00   Length:9915        Length:9915        Length:9915       \n 1st Qu.: 27.00   Class :character   Class :character   Class :character  \n Median : 37.00   Mode  :character   Mode  :character   Mode  :character  \n Mean   : 39.68                                                           \n 3rd Qu.: 50.00                                                           \n Max.   :100.00                                                           \n                                                                          \n    c8n_a1             c8n_a2             c8n_b1             c8n_b2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c8n_c1             c8n_c2             c8n_d1             c8n_d2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c8n_e1             c8n_e2             c8n_f1             c8n_f2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c12_1              c12_2              c12_3              c12_4          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     c22                c14                c15                C16           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c16_unit           c17_1__1           c17_1__2           c17_1__3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c17_1__4           c17_1__5           c17_1__6           c17_1__7        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c17_1__8           c17_1__9          c17_1__10          c17_1__11        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c18_1__1           c18_1__2           c18_1__3           c18_1__4        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c18_1__5           c18_1__6           c18_1__7           c18_1__8        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c18_1__9          c18_1__10          c18_1__11          c18_1__12        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c18_2               c19               c20_1              c20_2          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c23__1             c23__2             c23__3             c24_2          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c24_2a             C24_3              c24_1              c25__1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c25__2            c25X1__1           c25X1__3           c25X1__4        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c25X1__5           c25X1__6           c25X2__1           c25X2__2        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c25X2__3           c25X2__4           c25X2__5           c25X2__6        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     c26               c27__1             c27__2             c27__3         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c27__4             c27__5             c27__6             c27__7         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    c27__8             c27__9            c27__10            c27__11         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c27__12            c27__13            c27__14            c27__15         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c27__16            c27__18            c27__19            c27__20         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   c27__17              D_1              D2_1__1            D2_1__2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D2_1__3            D2_1__4            D2_1__5            D2_1__6         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D2_1__7            D2_1__8            D2_1__9            D2_1__10        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D2_1__11           D2_1__12             D2_4               D3_1          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     D3_2                D4                 D5                D5a           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     D5b                D6_1_1           D6_1_2           D6_1_3      \n Length:9915        Min.   : 0.000   Min.   : 0.000   Min.   : 0.000  \n Class :character   1st Qu.: 0.000   1st Qu.: 0.000   1st Qu.: 0.000  \n Mode  :character   Median : 0.000   Median : 0.000   Median : 2.000  \n                    Mean   : 0.442   Mean   : 0.863   Mean   : 2.881  \n                    3rd Qu.: 0.000   3rd Qu.: 1.000   3rd Qu.: 3.000  \n                    Max.   :60.000   Max.   :20.000   Max.   :59.000  \n                    NA's   :4727     NA's   :9303     NA's   :9303    \n     D6_2               D6_3             D6_3a__1           D6_3a__2        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D6_3a__3           D6_3a__4           D6_3a__5           D6_3a__6        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D6_3a__7           D6_3a__8             D6_4              D6_4a          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    D6_4b             D6_4c__1           D6_4c__2           D6_4c__3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D6_4c__4           D6_4c__5           D6_4c__6           D6_4c__7        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   D6_4c__8           D6_4c__9          D6_4c__10              D7           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     D7a                D7b                D7c                D7d           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    e_1_1             e_1_1new             e_2              e_3_3__1        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   e_3_3__2           e_3_3__3           e_3_3__4           e_3_3__5        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   e_3_3__6           e_3_3__7           e_3_3__8           e_3_3__9        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  e_3_3__11          e_3_3__12          e_3_3__13          e_3_3__14        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  e_3_3__15          e_3_3__16             e_4                e_4n          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   e_5_1           e_5_2           e_5_n_1            e_5_n_2         \n Mode :logical   Mode :logical   Length:9915        Length:9915       \n FALSE:4413      FALSE:8432      Class :character   Class :character  \n TRUE :5502      TRUE :1483      Mode  :character   Mode  :character  \n                                                                      \n                                                                      \n                                                                      \n                                                                      \n     e_6                e_7             e_7_n_1__1         e_7_n_1__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  e_7_n_1__3         e_7_n_1__4         e_7_n_1__5         e_7_n_1__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  e_7_n_1__7         e_7_n_1__8         e_7_n_1__9        e_7_n_1__10       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   e_7_n_2            e_7_n_3            e_7_n_4              e_10          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    e_11_1             e_11_2           e_11_2_n_1         e_11_2_n_2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  e_11_2_n_3           e_12_1             e_12_2             e_12_4         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     e_13             E14_1__1           E14_1__2           E14_1__3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   E14_1__4           E14_1__5           E14_1__6             f_2           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   f_3_1_1            f_3_1_2           f_3_2_1__1         f_3_2_1__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  f_3_2_1__3         f_3_2_1__4         f_3_2_1__5         f_3_2_1__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  f_3_2_1__7         f_3_2_1__8         f_3_2_1__9          f_3_2_2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   F4_1__1            F4_1__2            F4_1__3            F4_1__4         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   F4_1__5            F4_1__6            F4_1__7            F4_1__8         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   F4_1__9            F4_1__10           F4_1__11           F4_1__12        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   F4_1__13           F4_1__14             F4_4               F4_5          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     f_5             f_5_n_1__1         f_5_n_1__2         f_5_n_1__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  f_5_n_1__4         f_5_n_1__5         f_5_n_2__1         f_5_n_2__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  f_5_n_2__3         f_5_n_2__4         f_5_n_2__5           f_7_1          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    f_7_2              f_8_1              f_8_2               f_9           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   g_1_1_1            g_1_1_4            g_1_1_7            g_1_1_8         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  g_1_2_1__1         g_1_2_1__2         g_1_2_1__3         g_1_2_1__4       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  g_1_2_1__5         g_1_2_1__6         g_1_2_1__7         g_1_2_1__8       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  g_1_2_1__9        g_1_2_1__10          g_1_2_2            g_2_1_1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   g_2_1_2             g_2_2              g_2_3              g_2_4          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    g_2_5              g_2_6              g_2_6n              g_4           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   g_5_1__1           g_5_1__2           g_5_1__3           g_5_1__5        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   g_5_1__6           g_5_1__7           g_5_1__8           g_5_1__9        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  g_5_1__10          g_5_1__11          g_5_1__12          g_5_1__13        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  g_5_1__14           g_5_2__1           g_5_2__2           g_5_2__3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n g_5_2__5         g_5_2__6           g_5_2__7           g_5_2__8        \n Mode:logical   Length:9915        Length:9915        Length:9915       \n NA's:9915      Class :character   Class :character   Class :character  \n                Mode  :character   Mode  :character   Mode  :character  \n                                                                        \n                                                                        \n                                                                        \n                                                                        \n   g_5_2__9          g_5_2__10          g_5_2__11          g_5_2__12        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n g_5_2__13       g_5_2__14            g_5_3               g_6           \n Mode:logical   Length:9915        Length:9915        Length:9915       \n NA's:9915      Class :character   Class :character   Class :character  \n                Mode  :character   Mode  :character   Mode  :character  \n                                                                        \n                                                                        \n                                                                        \n                                                                        \n     g_7               g_8_1              g_8_2               g_9           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    g_12_1             g_12_2             g_13_1             pay_1          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   pay_1_4            pay_1_5            pay_1_6            pay_1_7         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   pay_1_8           pay2_1__1          pay2_1__2          pay2_1__3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  pay2_1__4          pay2_1__5          pay2_1__6          pay2_1__7        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    pay3_1             pay4_1           pay5_1__1          pay5_1__2        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  pay5_1__3          pay5_1__4          pay5_1__5          pay5_1__6        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  pay5_1__7            pay6_1              pb1                pb2           \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     pb3                pb4                pb5               pb2_1          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    pb2_2              pb2_3              pb2_4              pb2_5          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    pb2_6              pb3_1              pb3_2              pb3_3          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    pb3_4              pb4_1              pb4_2              pb4_3          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    pb4_4              pb4_5              pb4_6              pb4_7          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   gov_1__1           gov_1__2           gov_1__3           gov_1__4        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   gov_2__1           gov_2__2           gov_2__3           gov_2__4        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   gov_2__5           gov_2__6           gov_2__7             gov_3       \n Length:9915        Length:9915        Length:9915        Min.   : 10000  \n Class :character   Class :character   Class :character   1st Qu.: 24000  \n Mode  :character   Mode  :character   Mode  :character   Median : 35000  \n                                                          Mean   : 42999  \n                                                          3rd Qu.: 48000  \n                                                          Max.   :500000  \n                                                          NA's   :9740    \n    bill_1            bill2_1            bill2_2            bill2_3         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   bill2_4            bill2_5           serv1_1__1         serv1_1__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  serv1_1__3         serv1_1__4         serv1_1__5         serv1_1__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  serv1_1__7         serv1_1__8         serv1_1__9        serv1_1__10       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n serv1_1__11        serv1_1__12          serv1_2            serv1_3         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   serv1_5            serv1_6           serv1_7__1         serv1_7__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  serv1_7__3         serv1_7__4          serv1_8            serv3_1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   serv5_0            serv5_1           serv2_1__1         serv2_1__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  serv2_1__3         serv2_1__4         serv2_1__5          serv2_2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   serv2_3          serv2_4          comm3_1            comm4_1         \n Length:9915        Mode:logical   Length:9915        Length:9915       \n Class :character   NA's:9915      Class :character   Class :character  \n Mode  :character                  Mode  :character   Mode  :character  \n                                                                        \n                                                                        \n                                                                        \n                                                                        \n   comm6_2            comm6_3            comm6_3a          comm7_1__1       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  comm7_1__2         comm7_1__3         comm7_1__4         comm7_1__5       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   comm7_2           comm8_1__1         comm8_1__2         comm8_1__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  comm8_1__4         comm8_1__5         comm8_1__6         comm8_1__7       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n comm8_1a__1        comm8_1a__3        comm8_1a__4        comm8_1a__5       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n comm8_1a__6          comm9_1            comm10_1           micro5_1        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   micro1_1         micro2_1__1        micro2_1__2        micro2_1__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n micro2_1__4          micro2_2           micro2_3           micro2_4        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   micro2_5           micro4_0           micro6_2           micro6_3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n micro7_1__1        micro7_1__2        micro7_1__3        micro7_1__4       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n micro7_1__5          micro7_2         micro8_0__1        micro8_0__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n micro8_0__3        micro8_0__4        micro8_0__5        micro8_0__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   micro9_0         micro9_0a__1       micro9_0a__2       micro9_0a__3      \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n micro9_0a__4       micro9_0a__6        micro10_0           cred1_1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   cred1_2            cred2_1           cred3_1__1         cred3_1__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cred3_1__3         cred3_1__4         cred3_1__5         cred3_1__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cred3_1__7         cred3_1__8        cred3_1a__1        cred3_1a__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n cred3_1a__3        cred3_1a__4        cred3_1a__5        cred3_1a__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cred3_2__1         cred3_2__2         cred3_2__3         cred3_2__4       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cred3_2__5         cred3_2__6         cred3_2__7         cred3_2__8       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cred3_2__9          cred4_2            cred4_3            cred5_1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   cred5_2            cred6_1            cred6_2            cred9_0         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    pens1              pens2              pens3              pens4          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    ins1_1             ins1_2           ins1_3__1          ins1_3__2        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins1_3__3          ins1_3__4             ins2            ins3_1__1        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins3_1__2          ins3_1__3          ins3_1__4          ins3_1__5        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins3_1__6          ins3_1__7          ins3_1__8          ins3_1__9        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins3_1__10         ins3_1__11         ins3_1__12         ins3_1__13       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins3_1__14         ins3_1__15         ins3_1__16         ins3_1__17       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins3_1__18           ins3_5             ins4_1             ins4_2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins4_2a__1         ins4_2a__2         ins4_2a__3         ins4_2a__4       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins4_2a__5         ins4_2a__6            ins5              ins6_1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    ins6_2           ins6_2a__1         ins6_2a__2         ins6_2a__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  ins6_2a__4           mob1_3             mob1_4             mob1_6         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    mob1_7             mob1_8             mob1_9            mob1_10         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     mob2               mob3               mob4               mob5          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    mob5a              mob5b              mob5c              mob5d          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    mob5e              mob5f              mob5g               mob6          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     mob7             mob8__1            mob8__2            mob8__3         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   mob8__4            mob8__5            mob8__6             mob9_2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    mob9_3           mob10_1__1         mob10_1__2         mob10_1__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob10_1__4         mob10_1__5         mob10_1__6         mob10_1__7       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob10_2__1         mob10_2__2         mob10_2__3         mob10_2__4       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   mob11_1           mob11_2__1         mob11_2__2         mob11_2__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   mob11_3             mob12              mob13              mob14          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    mob15             mob16_1           mob16_2__1         mob16_2__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob16_2__3         mob16_2__4         mob16_2__5         mob16_2__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob16_2__7         mob16_2__8           mob17            mob17a__1        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob17a__2          mob17a__3          mob17a__4          mob17a__5        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob17a__6          mob17a__7            mob17b             mob17c         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    mob17d             mob17e           mob17f__1          mob17f__2        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  mob17f__3          mob17f__4           cmg1__1            cmg1__2         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   cmg1__3            cmg1__4             cmg1a               cmg2          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     cmg3            cmg4_1__1          cmg4_1__2          cmg4_1__3        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_1__4          cmg4_1__5          cmg4_1__6          cmg4_1__7        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_2__1          cmg4_2__2          cmg4_2__3          cmg4_2__4        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_2__5          cmg4_2__6          cmg4_2__7          cmg4_2__8        \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_2__9          cmg4_2__10         cmg4_2a__1         cmg4_2a__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_2a__3         cmg4_2a__4         cmg4_2a__5         cmg4_2a__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_2a__7            cmg4_3            cmg4_4             cmg4_7         \n Length:9915        Min.   :     0.0   Length:9915        Length:9915       \n Class :character   1st Qu.:     1.0   Class :character   Class :character  \n Mode  :character   Median :     1.0   Mode  :character   Mode  :character  \n                    Mean   :   179.2                                        \n                    3rd Qu.:     1.0                                        \n                    Max.   :150000.0                                        \n                    NA's   :8970                                            \n     cmg4_8           cmg4_9            cmg4_10            cmg4_11         \n Min.   :      0   Length:9915        Length:9915        Length:9915       \n 1st Qu.:   5000   Class :character   Class :character   Class :character  \n Median :  10000   Mode  :character   Mode  :character   Mode  :character  \n Mean   :  24465                                                           \n 3rd Qu.:  20750                                                           \n Max.   :1000000                                                           \n NA's   :8977                                                              \n   cmg4_12           cmg4_13__1         cmg4_13__2         cmg4_13__3       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_13__4         cmg4_13__5         cmg4_13__6         cmg4_13__7       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  cmg4_13__8          cmg4_14          cmg4_14a__1        cmg4_14a__2       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n cmg4_14a__3        cmg4_14a__4        cmg4_14a__5        cmg4_14a__6       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n cmg4_14a__7        cmg4_14a__8        cmg4_14a__9          lender1         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   lender3             lender4          lender4a         lender4b__1       \n Length:9915        Min.   :   1000   Length:9915        Length:9915       \n Class :character   1st Qu.:  25000   Class :character   Class :character  \n Mode  :character   Median :  50000   Mode  :character   Mode  :character  \n                    Mean   : 117429                                        \n                    3rd Qu.: 150000                                        \n                    Max.   :3000000                                        \n                    NA's   :9628                                           \n lender4b__2        lender4b__3        lender4b__4        lender4b__5       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n lender4b__6          lender5             k_1_1              k_1_2          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    k_2_1              k_2_2              k_2_3              k_2_4          \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n    k_3__1             k_3__2             k_3__3             k_3__4         \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n      RU                 MZ                tot            Household_weight  \n Length:9915        Length:9915        Length:9915        Min.   :   50.71  \n Class :character   Class :character   Class :character   1st Qu.:  515.84  \n Mode  :character   Mode  :character   Mode  :character   Median : 1040.76  \n                                                          Mean   : 1427.35  \n                                                          3rd Qu.: 1745.86  \n                                                          Max.   :11680.64  \n                                                                            \n population_wt           MM               BANKED              MFI           \n Min.   :   73.48   Length:9915        Length:9915        Length:9915       \n 1st Qu.: 1174.56   Class :character   Class :character   Class :character  \n Median : 2287.63   Mode  :character   Mode  :character   Mode  :character  \n Mean   : 3442.69                                                           \n 3rd Qu.: 4175.85                                                           \n Max.   :50600.52                                                           \n                                                                            \n   PENSION           INSURANCE            SACCO          \n Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n                                                         \n CAPITALM_FUND_MANAGERS FORM_INVESTMENTS       CMG           \n Length:9915            Length:9915        Length:9915       \n Class :character       Class :character   Class :character  \n Mode  :character       Mode  :character   Mode  :character  \n                                                             \n                                                             \n                                                             \n                                                             \n INFORMAL_MONEYLENDER SOCIAL_GROUPS      OTHER_FORMAL       OVERALL_FORMAL    \n Length:9915          Length:9915        Length:9915        Length:9915       \n Class :character     Class :character   Class :character   Class :character  \n Mode  :character     Mode  :character   Mode  :character   Mode  :character  \n                                                                              \n                                                                              \n                                                                              \n                                                                              \n   INFORMAL             fasx             overlapx          IncomeMain       \n Length:9915        Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n     BusO           DEDICATED_FARMER   SMALLHOLDER_FARMER\n Length:9915        Length:9915        Length:9915       \n Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character  \n                                                         \n                                                         \n                                                         \n                                                         \n```\n\n\n:::\n:::\n\n\n### 5.2 Data Cleanup\n\nGiven that the tz tibble data frame contains 721 columns, we first want to cleanup the dataset and only retain the fields that we want to focus our analysis on. Some of the fields we can consider for our analysis are:\n\n1.  Overall Formal: this combines all variables that indicate formal financial service usage by an individual\n\n2.  Informal: this combines all variables that indicate informal financial service usage by an individual\n\n3.  Income Main: the main source of income for an individual\n\n4.  Dedicated Farmer: whether the individual is a dedicated farmer or not, meaning more than 50% of their income originates from farming\n\n5.  Banked: this combines all variables that indicate bank service usage by an individual\n\n6.  \\(MM\\) Mobile: this combines all variables that indicate mobile money usage by an individual\n\n7.  Insurance: this combines all variables that indicate any insurance usage by an individual\n\n8.  (Form) Investments: this combines all variables that indicate formal investment mechanisms usage by an individual\n\n9.  Pension: this combines all variables that indicate pension service usage by an individual\n\n## 6.0 Exploratory Data Analysis\n\nx\n\n## 7.0 Financial Inclusion Model\n\nx\n\n## 8.0 Using gwModel\n\nx\n",
    "supporting": [
      "Take-Home_Ex03A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}