---
title: "In-Class Exercise 02"
author: "Bhairavi Vairavelu"
date: "Sep 02 2024"
date-modified: "last-modified"
execute:
  eval: true
  echo: true
  message: false
  freeze: true
---

## 1. Install R Packages

The code chunk below is used to install and launch R packages:

```{r}
pacman::p_load(sf, raster, spatstat, tmap, tidyverse)
```

Installing maptools:

```{r}
#|eval: false
install.packages("maptools", repos = "https://packagemanager.posit.co/cran/2023-10-13")
```

## 2. Load Data

```{r}
#|eval: false
childcare_sf <- st_read("data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
write_rds(childcare_sf, "data/rds/childcare_sf.rds")
```

To read in the rds:

```{r}
childcare_sf <- read_rds("data/rds/childcare_sf.rds")
```

```{r}
#|eval: false
sg_sf <- st_read(dsn = "data", layer="CostalOutline")
write_rds(sg_sf, "data/rds/sg_sf.rds")
```

To read in the rds:

```{r}
sg_sf <- read_rds("data/rds/sg_sf.rds")
```

```{r}
#|eval: false
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
write_rds(mpsz_sf, "data/rds/mpsz_sf.rds")
```

To read in the rds:

```{r}
mpsz_sf <- read_rds("data/rds/mpsz_sf.rds")
```

## 3. Data Wrangling

```{r}
sg_sf <- mpsz_sf %>%
  st_union()
```

```{r}
sg_sf
```

```{r}
#|eval: false
sg_sf3414 <- st_set_crs(sg_sf, 3414)
write_rds(sg_sf3414, "data/rds/sg_sf3414.rds")
```

To read in the rds:

```{r}
sg_sf3414 <- read_rds("data/rds/sg_sf3414.rds")
```

```{r}
st_crs(sg_sf3414)
```

## 4. Geospatial Data Wrangling

```{r}
childcare <- as_Spatial(childcare_sf)
childcare_sp <- as(childcare, "SpatialPoints")
childcare_ppp <- as.ppp(childcare_sf)
```

```{r}
sg_owin <- as.owin(sg_sf)
childcareSG_ppp = childcare_ppp[sg_owin]
childcareSG_ppp.km <- rescale.ppp(childcareSG_ppp, 1000, "km")
```

```{r}
kde_childcareSG_adaptive <- adaptive.density(childcareSG_ppp.km, method="kernel")
```

```{r}
gridded_kde_childcareSG_ad <- as(
  kde_childcareSG_adaptive,
  "SpatialGridDataFrame"
)
spplot(gridded_kde_childcareSG_ad)
```

```{r}
set.seed(1234)
```
