<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bhairavi Vairavelu">
<meta name="dcterms.date" content="2024-09-02">

<title>ISSS626-GAA - Take-Home Exercise 01</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-On Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01A.html">
 <span class="dropdown-text">Hands-On Exercise 01A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01B.html">
 <span class="dropdown-text">Hands-On Exercise 01B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02A.html">
 <span class="dropdown-text">Hands-On Exercise 02A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02B.html">
 <span class="dropdown-text">Hands-On Exercise 02B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-On Exercise 03</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-On Exercise 04</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05A/Hands-on_Ex05A.html">
 <span class="dropdown-text">Hands-On Exercise 05A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B/Hands-on_Ex05B.html">
 <span class="dropdown-text">Hands-On Exercise 05B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-On Exercise 06</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex01/In-Class_Ex01_1.html">
 <span class="dropdown-text">In-Class Exercise 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html">
 <span class="dropdown-text">In-Class Exercise 02</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html">
 <span class="dropdown-text">In-Class Exercise 03</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html">
 <span class="dropdown-text">In-Class Exercise 04</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html">
 <span class="dropdown-text">In-Class Exercise 05</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Ex/In-Class_Ex06/In-Class_Ex06.html">
 <span class="dropdown-text">In-Class Exercise 06</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex1D.html">
 <span class="dropdown-text">Take-Home Exercise 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02D.html">
 <span class="dropdown-text">Take-Home Exercise 02</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#geospatial-analytics-for-public-good" id="toc-geospatial-analytics-for-public-good" class="nav-link active" data-scroll-target="#geospatial-analytics-for-public-good">Geospatial Analytics for Public Good</a>
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">1. Overview</a></li>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">2. Getting Started</a>
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">2.1 Objectives</a></li>
  <li><a href="#the-study-area" id="toc-the-study-area" class="nav-link" data-scroll-target="#the-study-area">2.2 The Study Area</a></li>
  <li><a href="#analytical-tools" id="toc-analytical-tools" class="nav-link" data-scroll-target="#analytical-tools">2.3 Analytical Tools</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">3. Data</a>
  <ul>
  <li><a href="#getting-the-data" id="toc-getting-the-data" class="nav-link" data-scroll-target="#getting-the-data">3.1 Getting the Data</a></li>
  <li><a href="#storing-the-data" id="toc-storing-the-data" class="nav-link" data-scroll-target="#storing-the-data">3.2 Storing the Data</a></li>
  <li><a href="#importing-the-data" id="toc-importing-the-data" class="nav-link" data-scroll-target="#importing-the-data">3.3 Importing the Data</a>
  <ul class="collapse">
  <li><a href="#thailand-roads-data" id="toc-thailand-roads-data" class="nav-link" data-scroll-target="#thailand-roads-data">3.3.1 Thailand Roads Data</a></li>
  <li><a href="#thailand---subnational-administrative-boundaries-data" id="toc-thailand---subnational-administrative-boundaries-data" class="nav-link" data-scroll-target="#thailand---subnational-administrative-boundaries-data">3.3.2 Thailand - Subnational Administrative Boundaries Data</a></li>
  <li><a href="#thailand-road-accidents-data" id="toc-thailand-road-accidents-data" class="nav-link" data-scroll-target="#thailand-road-accidents-data">3.3.3 Thailand Road Accidents Data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">4. Data Wrangling</a>
  <ul>
  <li><a href="#aspatial-data-wrangling" id="toc-aspatial-data-wrangling" class="nav-link" data-scroll-target="#aspatial-data-wrangling">4.1 Aspatial Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#removing-columns" id="toc-removing-columns" class="nav-link" data-scroll-target="#removing-columns">4.1.1 Removing Columns</a></li>
  <li><a href="#adding-columns" id="toc-adding-columns" class="nav-link" data-scroll-target="#adding-columns">4.1.2 Adding Columns</a></li>
  <li><a href="#filter-by-province" id="toc-filter-by-province" class="nav-link" data-scroll-target="#filter-by-province">4.1.3 Filter by Province</a></li>
  <li><a href="#handling-missing-values" id="toc-handling-missing-values" class="nav-link" data-scroll-target="#handling-missing-values">4.1.4 Handling Missing Values</a></li>
  <li><a href="#handling-duplicates" id="toc-handling-duplicates" class="nav-link" data-scroll-target="#handling-duplicates">4.1.5 Handling Duplicates</a></li>
  <li><a href="#creating-simple-feature-data-frame" id="toc-creating-simple-feature-data-frame" class="nav-link" data-scroll-target="#creating-simple-feature-data-frame">4.1.6 Creating Simple Feature Data Frame</a></li>
  </ul></li>
  <li><a href="#geospatial-data-wrangling" id="toc-geospatial-data-wrangling" class="nav-link" data-scroll-target="#geospatial-data-wrangling">4.2 Geospatial Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#removing-columns-1" id="toc-removing-columns-1" class="nav-link" data-scroll-target="#removing-columns-1">4.2.1 Removing Columns</a></li>
  <li><a href="#filter-by-province-1" id="toc-filter-by-province-1" class="nav-link" data-scroll-target="#filter-by-province-1">4.2.2 Filter by Province</a></li>
  <li><a href="#filter-by-highway" id="toc-filter-by-highway" class="nav-link" data-scroll-target="#filter-by-highway">4.2.3 Filter by Highway</a></li>
  <li><a href="#handling-multilinestring" id="toc-handling-multilinestring" class="nav-link" data-scroll-target="#handling-multilinestring">4.2.4 Handling Multilinestring</a></li>
  <li><a href="#coordinate-systems" id="toc-coordinate-systems" class="nav-link" data-scroll-target="#coordinate-systems">4.2.5 Coordinate Systems</a></li>
  <li><a href="#intersection-of-data" id="toc-intersection-of-data" class="nav-link" data-scroll-target="#intersection-of-data">4.2.6 Intersection of Data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#visualizing-spatio-temporal-dynamics-of-accidents" id="toc-visualizing-spatio-temporal-dynamics-of-accidents" class="nav-link" data-scroll-target="#visualizing-spatio-temporal-dynamics-of-accidents">5. Visualizing Spatio-Temporal Dynamics of Accidents</a></li>
  <li><a href="#spatial-analysis-using-network-spatial-point-patterns-analysis" id="toc-spatial-analysis-using-network-spatial-point-patterns-analysis" class="nav-link" data-scroll-target="#spatial-analysis-using-network-spatial-point-patterns-analysis">6. Spatial Analysis using Network Spatial Point Patterns Analysis</a></li>
  <li><a href="#spatio-temporal-analysis-using-temporal-network-spatial-point-patterns-analysis" id="toc-spatio-temporal-analysis-using-temporal-network-spatial-point-patterns-analysis" class="nav-link" data-scroll-target="#spatio-temporal-analysis-using-temporal-network-spatial-point-patterns-analysis">7. Spatio-Temporal Analysis using Temporal Network Spatial Point Patterns Analysis</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home Exercise 01</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Bhairavi Vairavelu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 2, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 23, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="geospatial-analytics-for-public-good" class="level1">
<h1>Geospatial Analytics for Public Good</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">1. Overview</h2>
<p>Road traffic accidents result in significant human and economic costs worldwide, with approximately 1.19 million deaths annually and 20-50 million non-fatal injuries, particularly affecting vulnerable road users. In Thailand, about 20,000 people die each year, making it one of the deadliest countries for road accidents. Accidents frequently occur on national highways, with 66% happening on straight roads and specific high-risk zones like curves, intersections and steep slopes.</p>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">2. Getting Started</h2>
<section id="objectives" class="level3">
<h3 class="anchored" data-anchor-id="objectives">2.1 Objectives</h3>
<p>This analysis aims to discover factors that influence road traffic accidents by examining both behavioural and environmental causes through spatial and spatio-temporal point patterns. This includes:</p>
<ol type="1">
<li><p>Visualizing spatio-temporal dynamics of accidents</p></li>
<li><p>Conducting spatial analysis using Network Spatial Point Patterns Analysis</p></li>
<li><p>Conducting spatio-temporal analysis using Temporal Network Spatial Point Patterns Analysis</p></li>
</ol>
</section>
<section id="the-study-area" class="level3">
<h3 class="anchored" data-anchor-id="the-study-area">2.2 The Study Area</h3>
<p>The focus of this study would be the Bangkok Metropolitan Region (BMR).</p>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="BMR2.png" class="img-fluid quarto-figure quarto-figure-left figure-img" width="300"></p>
</figure>
</div>
<p>Note: The projected coordinate system of Thailand is WGS84/UTM zone 47N, and the EPSG code is 32647.</p>
</section>
<section id="analytical-tools" class="level3">
<h3 class="anchored" data-anchor-id="analytical-tools">2.3 Analytical Tools</h3>
<p>The p_load function of pacman package is used to install and loads the analytical tools that we will be using throughout this exercise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, sfdep, tidyverse, tmap, Hmisc, lubridate, spNetwork, ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>sf for importing, managing, and processing geospatial data</p></li>
<li><p>sfdep for computing spatial weights and autocorrelation statistics</p></li>
<li><p>tidyverse for performing data science tasks such as importing, wrangling and visualizing data</p></li>
<li><p>tmap for visualizing geospatial objects</p></li>
<li><p>Hmisc for summary statistics</p></li>
<li><p>lubridate for parsing and manipulating dates</p></li>
<li><p>spNetwork for spatial point pattern analysis</p></li>
<li><p>ggplot2 for plotting graphs</p></li>
</ul>
</section>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">3. Data</h2>
<section id="getting-the-data" class="level3">
<h3 class="anchored" data-anchor-id="getting-the-data">3.1 Getting the Data</h3>
<p>Three basic data sets will be used for this analysis:</p>
<ol type="1">
<li>Thailand Road Accident [2019-2022] on Kaggle</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Data01.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Link: <a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022" class="uri">https://www.kaggle.com/datasets/thaweewatboy/thailand-road-accident-2019-2022</a></p>
<p>Note: a Kaggle account is required in order to download this dataset.</p>
<ol start="2" type="1">
<li>Thailand Roads (OpenStreetMap Export) on HDX</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Data02.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Link: <a href="https://data.humdata.org/dataset/hotosm_tha_roads" class="uri">https://data.humdata.org/dataset/hotosm_tha_roads</a></p>
<ol start="3" type="1">
<li>Thailand - Subnational Administrative Boundaries on HDX</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Data03_1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Link: <a href="https://data.humdata.org/dataset/cod-ab-tha?" class="uri">https://data.humdata.org/dataset/cod-ab-tha?</a></p>
</section>
<section id="storing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="storing-the-data">3.2 Storing the Data</h3>
<p>At the Take-Home_Ex01 folder, we will create a sub-folder called data. Then, within this sub-folder, we will organize the data sets accordingly:</p>
<ul>
<li><p>data/geospatial will store geospatial data</p></li>
<li><p>data/aspatial will store aspatial data</p></li>
<li><p>data/rds will be used to store the outputs we save so that we can reuse and make our code reproducible</p></li>
</ul>
</section>
<section id="importing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-the-data">3.3 Importing the Data</h3>
<section id="thailand-roads-data" class="level4">
<h4 class="anchored" data-anchor-id="thailand-roads-data">3.3.1 Thailand Roads Data</h4>
<p>The code chunk below uses st_read() function of sf package to import the hotosm_tha_roads_lines_shp shapefile into R as a simple feature data frame. For this code chunk, we will define the data path and the layer to provide the shapefile name. The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>thaiRoadsRaw <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">layer =</span> <span class="st">"hotosm_tha_roads_lines_shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `hotosm_tha_roads_lines_shp' from data source 
  `C:\byebhai8\ISSS626-GeospatialAnalytics\Take-Home_Ex\Take-Home_Ex01\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 2792590 features and 14 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 97.34457 ymin: 5.643645 xmax: 105.6528 ymax: 20.47168
CRS:           NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(thaiRoadsRaw, <span class="st">"data/rds/thaiRoadsRaw.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved thaiRoadsRaw.rds into R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>thaiRoadsRaw <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/thaiRoadsRaw.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">road =</span> name_en)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thaiRoadsRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,792,590
Columns: 15
$ name       &lt;chr&gt; "ถนนฉลองกรุง", "ซอยฉลองกรุง 1/1", NA, NA, "ถนนฉลองกรุง", NA, "…
$ road       &lt;chr&gt; "Chalong Krung Road", "Soi Chalong Krung 1/1", NA, NA, "Cha…
$ highway    &lt;chr&gt; "secondary", "residential", "secondary_link", "service", "s…
$ surface    &lt;chr&gt; "paved", NA, NA, NA, "concrete", NA, NA, "unpaved", NA, NA,…
$ smoothness &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ width      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ lanes      &lt;chr&gt; NA, NA, NA, NA, "2", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ oneway     &lt;chr&gt; "yes", NA, "yes", NA, "yes", NA, NA, NA, NA, NA, NA, NA, NA…
$ bridge     &lt;chr&gt; NA, NA, NA, NA, "yes", NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ layer      &lt;chr&gt; NA, NA, NA, NA, "1", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ source     &lt;chr&gt; NA, NA, NA, NA, "Bing", NA, NA, "GPS", NA, NA, NA, NA, NA, …
$ name_th    &lt;chr&gt; "ถนนฉลองกรุง", "ซอยฉลองกรุง 1/1", NA, NA, "ถนนฉลองกรุง", NA, "…
$ osm_id     &lt;dbl&gt; 1125681229, 594401607, 472283206, 594401608, 116847248, 317…
$ osm_type   &lt;chr&gt; "ways_line", "ways_line", "ways_line", "ways_line", "ways_l…
$ geometry   &lt;MULTILINESTRING&gt; MULTILINESTRING ((100.7913 ..., MULTILINESTRING…</code></pre>
</div>
</div>
<p>thaiRoadsRaw has a total of 2,792,590 features and 15 fields, with geometry type of multilinestring, and the coordinate system is currently NA.</p>
</section>
<section id="thailand---subnational-administrative-boundaries-data" class="level4">
<h4 class="anchored" data-anchor-id="thailand---subnational-administrative-boundaries-data">3.3.2 Thailand - Subnational Administrative Boundaries Data</h4>
<p>Likewise, the code chunk below will use the st_read() function of sf package to import the tha_admbndp_admALL_rtsd_itos_20220121 shapefile into R as a simple feature data frame. The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>admBndpRaw <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">"tha_admbnda_adm1_rtsd_20220121"</span>) <span class="co">#tha_admbndp_admALL_rtsd_itos_20220121</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tha_admbnda_adm1_rtsd_20220121' from data source 
  `C:\byebhai8\ISSS626-GeospatialAnalytics\Take-Home_Ex\Take-Home_Ex01\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(admBndpRaw, <span class="st">"data/rds/admBndpRaw.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved admBndpRaw.rds into R environment. Note that there are 2 administrative levels in this data set - ADM0 for country, and ADM1 for province. Hence, we will rename ADM1_EN to province.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>admBndpRaw <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/admBndpRaw.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">province =</span> ADM1_EN)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(admBndpRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 77
Columns: 17
$ Shape_Leng &lt;dbl&gt; 2.417227, 1.695100, 1.251111, 1.884945, 3.041716, 1.739908,…
$ Shape_Area &lt;dbl&gt; 0.13133873, 0.07926199, 0.05323766, 0.12698345, 0.21393797,…
$ province   &lt;chr&gt; "Bangkok", "Samut Prakan", "Nonthaburi", "Pathum Thani", "P…
$ ADM1_TH    &lt;chr&gt; "กรุงเทพมหานคร", "สมุทรปราการ", "นนทบุรี", "ปทุมธานี", "พระนครศรีอ…
$ ADM1_PCODE &lt;chr&gt; "TH10", "TH11", "TH12", "TH13", "TH14", "TH15", "TH16", "TH…
$ ADM1_REF   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT1EN &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT2EN &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT1TH &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM1ALT2TH &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ADM0_EN    &lt;chr&gt; "Thailand", "Thailand", "Thailand", "Thailand", "Thailand",…
$ ADM0_TH    &lt;chr&gt; "ประเทศไทย", "ประเทศไทย", "ประเทศไทย", "ประเทศไทย", "ประเทศ…
$ ADM0_PCODE &lt;chr&gt; "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH", "TH",…
$ date       &lt;date&gt; 2019-02-18, 2019-02-18, 2019-02-18, 2019-02-18, 2019-02-18…
$ validOn    &lt;date&gt; 2022-01-22, 2022-01-22, 2022-01-22, 2022-01-22, 2022-01-22…
$ validTo    &lt;date&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((100.6139 13..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>admBndpRaw has a total of 77 features and 17 fields, with geometry type of multipolygon, and it is in wgs84 coordinates system.</p>
</section>
<section id="thailand-road-accidents-data" class="level4">
<h4 class="anchored" data-anchor-id="thailand-road-accidents-data">3.3.3 Thailand Road Accidents Data</h4>
<p>Since thai_road_accident_2019_2022.csv data file is in csv file format, we will use the read_csv() of readr package to import this data as shown in the code chunk below. Note that the output will be in a tibble data frame format, and this output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/thai_road_accident_2019_2022.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 81735 Columns: 18
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (10): province_th, province_en, agency, route, vehicle_type, presumed_c...
dbl   (6): acc_code, number_of_vehicles_involved, number_of_fatalities, numb...
dttm  (2): incident_datetime, report_datetime

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(thaiAccRaw, <span class="st">"data/rds/thaiAccRaw.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved thaiAccRaw.rds into R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/thaiAccRaw.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">province =</span> province_en)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(thaiAccRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 81,735 × 18
   acc_code incident_datetime   report_datetime     province_th province  agency
      &lt;dbl&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;chr&gt;       &lt;chr&gt;     &lt;chr&gt; 
 1   571905 2019-01-01 00:00:00 2019-01-02 06:11:00 ลพบุรี        Loburi    depar…
 2  3790870 2019-01-01 00:03:00 2020-02-20 13:48:00 อุบลราชธานี   Ubon Rat… depar…
 3   599075 2019-01-01 00:05:00 2019-01-01 10:35:00 ประจวบคีรีขันธ์ Prachuap… depar…
 4   571924 2019-01-01 00:20:00 2019-01-02 05:12:00 เชียงใหม่     Chiang M… depar…
 5   599523 2019-01-01 00:25:00 2019-01-04 09:42:00 นครสวรรค์    Nakhon S… depar…
 6   571982 2019-01-01 00:30:00 2019-01-07 12:46:00 แม่ฮ่องสอน    Mae Hong… depar…
 7   612782 2019-01-01 00:30:00 2019-10-25 14:25:00 ชุมพร        Chumphon  depar…
 8   599235 2019-01-01 00:35:00 2019-01-02 16:23:00 สิงห์บุรี       Sing Buri depar…
 9   600643 2019-01-01 00:40:00 2019-01-11 10:01:00 สงขลา       Songkhla  depar…
10   599105 2019-01-01 00:45:00 2019-01-01 10:11:00 ตราด        Trat      depar…
# ℹ 81,725 more rows
# ℹ 12 more variables: route &lt;chr&gt;, vehicle_type &lt;chr&gt;, presumed_cause &lt;chr&gt;,
#   accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;</code></pre>
</div>
</div>
<p>thaiAccRaw has a total of 81,735 features and 18 fields, including the latitude and longitude fields.</p>
</section>
</section>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">4. Data Wrangling</h2>
<section id="aspatial-data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="aspatial-data-wrangling">4.1 Aspatial Data Wrangling</h3>
<section id="removing-columns" class="level4">
<h4 class="anchored" data-anchor-id="removing-columns">4.1.1 Removing Columns</h4>
<p>It is likely that not all 18 columns are required/useful for our analysis, especially when some of the columns contain values that are not in English (province_th &amp; route). On top of this, there are 2 date columns in the data set - incident_datetime which represents when the accident occurred, and report_datetime which represent when the accident was reported. For the accuracy of our analysis, we only want to focus on when the accident occurred. Hence, we will remove this column as well.</p>
<p>We will use the select() function from dplyr package to select the variables by index, and exclude the indexes of the columns that we want to remove.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="ot">&lt;-</span> thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">8</span><span class="sc">:</span><span class="dv">18</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(thaiAccRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 81,735 × 15
   acc_code incident_datetime   province      agency vehicle_type presumed_cause
      &lt;dbl&gt; &lt;dttm&gt;              &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;         
 1   571905 2019-01-01 00:00:00 Loburi        depar… motorcycle   driving under…
 2  3790870 2019-01-01 00:03:00 Ubon Ratchat… depar… private/pas… speeding      
 3   599075 2019-01-01 00:05:00 Prachuap Khi… depar… motorcycle   speeding      
 4   571924 2019-01-01 00:20:00 Chiang Mai    depar… motorcycle   driving under…
 5   599523 2019-01-01 00:25:00 Nakhon Sawan  depar… private/pas… cutting in cl…
 6   571982 2019-01-01 00:30:00 Mae Hong Son  depar… motorcycle   speeding      
 7   612782 2019-01-01 00:30:00 Chumphon      depar… 4-wheel pic… failure to yi…
 8   599235 2019-01-01 00:35:00 Sing Buri     depar… motorcycle   speeding      
 9   600643 2019-01-01 00:40:00 Songkhla      depar… motorcycle   speeding      
10   599105 2019-01-01 00:45:00 Trat          depar… motorcycle   speeding      
# ℹ 81,725 more rows
# ℹ 9 more variables: accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;</code></pre>
</div>
</div>
<p>The output confirms that we have dropped 3 columns.</p>
</section>
<section id="adding-columns" class="level4">
<h4 class="anchored" data-anchor-id="adding-columns">4.1.2 Adding Columns</h4>
<p>We also want to add new columns which could potentially help with our analysis later on, namely Season, Day of Week and Time of Day. Reference was taken from the following link to determine the Seasons for BMR.</p>
<p>Link: <a href="https://www.thomascook.in/international-tourism/best-time-to-visit-bangkok#:~:text=The%20weather%20in%20Bangkok%20is,best%20time%20to%20visit%20Bangkok" class="uri">https://www.thomascook.in/international-tourism/best-time-to-visit-bangkok#:~:text=The%20weather%20in%20Bangkok%20is,best%20time%20to%20visit%20Bangkok</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="ot">&lt;-</span> thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">dayofweek =</span> <span class="fu">wday</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">season =</span> <span class="fu">case_when</span>(</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">month</span>(incident_datetime) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">11</span><span class="sc">:</span><span class="dv">12</span>) <span class="sc">~</span> <span class="st">"Winter"</span>, </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">month</span>(incident_datetime)  <span class="sc">%in%</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">6</span> <span class="sc">~</span> <span class="st">"Summer"</span>, </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">month</span>(incident_datetime)  <span class="sc">%in%</span> <span class="dv">7</span><span class="sc">:</span><span class="dv">10</span> <span class="sc">~</span> <span class="st">"Rainy"</span>))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(thaiAccRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 81,735 × 18
   acc_code incident_datetime   province      agency vehicle_type presumed_cause
      &lt;dbl&gt; &lt;dttm&gt;              &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;         
 1   571905 2019-01-01 00:00:00 Loburi        depar… motorcycle   driving under…
 2  3790870 2019-01-01 00:03:00 Ubon Ratchat… depar… private/pas… speeding      
 3   599075 2019-01-01 00:05:00 Prachuap Khi… depar… motorcycle   speeding      
 4   571924 2019-01-01 00:20:00 Chiang Mai    depar… motorcycle   driving under…
 5   599523 2019-01-01 00:25:00 Nakhon Sawan  depar… private/pas… cutting in cl…
 6   571982 2019-01-01 00:30:00 Mae Hong Son  depar… motorcycle   speeding      
 7   612782 2019-01-01 00:30:00 Chumphon      depar… 4-wheel pic… failure to yi…
 8   599235 2019-01-01 00:35:00 Sing Buri     depar… motorcycle   speeding      
 9   600643 2019-01-01 00:40:00 Songkhla      depar… motorcycle   speeding      
10   599105 2019-01-01 00:45:00 Trat          depar… motorcycle   speeding      
# ℹ 81,725 more rows
# ℹ 12 more variables: accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;, dayofweek &lt;ord&gt;,
#   month &lt;ord&gt;, season &lt;chr&gt;</code></pre>
</div>
</div>
<p>The output confirms that we have added 3 new columns.</p>
</section>
<section id="filter-by-province" class="level4">
<h4 class="anchored" data-anchor-id="filter-by-province">4.1.3 Filter by Province</h4>
<p>Note that thaiAccRaw has a total of 81,735 rows. We want to only focus on the study area (BMR) in our analysis. Hence, we will filter the province field to focus on the 6 provinces which are in the BMR: Bangkok, Nakhon Pathom, Pathum Thani, Nonthaburi, Samut Prakan and Samut Sakhon.</p>
<p>We will store these province names in a list and use it in our filter condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>bmr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Nakhon Pathom"</span>, <span class="st">"Pathum Thani"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Samut Prakan"</span>, <span class="st">"Samut Sakhon"</span>, <span class="st">"Bangkok"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="ot">&lt;-</span> thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province <span class="sc">%in%</span> bmr)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(thaiAccRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
# A tibble: 13,336 × 18
   acc_code incident_datetime   province      agency vehicle_type presumed_cause
      &lt;dbl&gt; &lt;dttm&gt;              &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;         
 1   571882 2019-01-01 02:25:00 Nakhon Pathom depar… motorcycle   speeding      
 2   600001 2019-01-01 03:00:00 Nonthaburi    depar… private/pas… speeding      
 3   605043 2019-01-01 03:00:00 Samut Prakan  depar… private/pas… running red l…
 4   629691 2019-01-01 03:05:00 Bangkok       expre… other        other         
 5   571887 2019-01-01 04:30:00 Nakhon Pathom depar… motorcycle   speeding      
 6   599234 2019-01-01 04:45:00 Samut Prakan  depar… motorcycle   driving under…
 7   599990 2019-01-01 05:30:00 Samut Sakhon  depar… motorcycle   speeding      
 8   612045 2019-01-01 05:30:00 Nonthaburi    depar… private/pas… cutting in cl…
 9   629689 2019-01-01 05:42:00 Bangkok       expre… other        other         
10   607046 2019-01-01 06:30:00 Pathum Thani  depar… private/pas… speeding      
# ℹ 13,326 more rows
# ℹ 12 more variables: accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;, dayofweek &lt;ord&gt;,
#   month &lt;ord&gt;, season &lt;chr&gt;</code></pre>
</div>
</div>
<p>Note that after the filter is applied, thaiAccRaw has been reduced to having only 13,336 rows.</p>
</section>
<section id="handling-missing-values" class="level4">
<h4 class="anchored" data-anchor-id="handling-missing-values">4.1.4 Handling Missing Values</h4>
<p>Moving forward, we will be utilizing two useful columns - latitude and longitude. Note that they are in decimal degree format.</p>
<p>The filter() function of dplyr package can be used to verify if these key columns have any missing values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(longitude) <span class="sc">|</span> longitude <span class="sc">==</span> <span class="st">""</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">is.na</span>(latitude)  <span class="sc">|</span> latitude <span class="sc">==</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 350 × 18
   acc_code incident_datetime   province agency      vehicle_type presumed_cause
      &lt;dbl&gt; &lt;dttm&gt;              &lt;chr&gt;    &lt;chr&gt;       &lt;chr&gt;        &lt;chr&gt;         
 1  5099638 2021-01-01 21:33:00 Bangkok  expressway… other        other         
 2  5099647 2021-01-10 14:26:00 Bangkok  expressway… other        other         
 3  3014701 2021-01-14 22:15:00 Bangkok  expressway… other        other         
 4  5099676 2021-01-26 02:00:00 Bangkok  expressway… other        other         
 5  5099678 2021-01-26 13:50:00 Bangkok  expressway… other        other         
 6  5099677 2021-01-26 17:39:00 Bangkok  expressway… other        other         
 7  5099691 2021-02-02 11:07:00 Bangkok  expressway… other        other         
 8  5099698 2021-02-03 21:47:00 Bangkok  expressway… other        other         
 9  5099703 2021-02-05 09:32:00 Bangkok  expressway… other        other         
10  5099716 2021-02-09 13:04:00 Bangkok  expressway… other        other         
# ℹ 340 more rows
# ℹ 12 more variables: accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;, dayofweek &lt;ord&gt;,
#   month &lt;ord&gt;, season &lt;chr&gt;</code></pre>
</div>
</div>
<p>The output proves that there are 350 rows which contain missing values for the latitude and longitude columns. To handle this issue, we will re-use the filter() function to exclude these missing values from our tibble data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="ot">&lt;-</span> thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(longitude) <span class="sc">|</span> longitude <span class="sc">!=</span> <span class="st">""</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(latitude)  <span class="sc">|</span> latitude <span class="sc">!=</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let us verify if the rows with missing values have been dropped by re-running our initial code chunk.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(longitude) <span class="sc">|</span> longitude <span class="sc">==</span> <span class="st">""</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">is.na</span>(latitude)  <span class="sc">|</span> latitude <span class="sc">==</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 18
# ℹ 18 variables: acc_code &lt;dbl&gt;, incident_datetime &lt;dttm&gt;, province &lt;chr&gt;,
#   agency &lt;chr&gt;, vehicle_type &lt;chr&gt;, presumed_cause &lt;chr&gt;,
#   accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;, dayofweek &lt;ord&gt;,
#   month &lt;ord&gt;, season &lt;chr&gt;</code></pre>
</div>
</div>
<p>The message above confirms that the rows with missing values have been excluded from thaiAccRaw.</p>
</section>
<section id="handling-duplicates" class="level4">
<h4 class="anchored" data-anchor-id="handling-duplicates">4.1.5 Handling Duplicates</h4>
<p>We also want to avoid the repetition of records, which could lead to incorrect analysis of accidents in thaiAccRaw. Hence, we will check for duplicates using group_by_all() to ensure the integrity of our data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>duplicates <span class="ot">&lt;-</span> thaiAccRaw <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by_all</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">n</span>()<span class="sc">&gt;</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>duplicates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 18
# ℹ 18 variables: acc_code &lt;dbl&gt;, incident_datetime &lt;dttm&gt;, province &lt;chr&gt;,
#   agency &lt;chr&gt;, vehicle_type &lt;chr&gt;, presumed_cause &lt;chr&gt;,
#   accident_type &lt;chr&gt;, number_of_vehicles_involved &lt;dbl&gt;,
#   number_of_fatalities &lt;dbl&gt;, number_of_injuries &lt;dbl&gt;,
#   weather_condition &lt;chr&gt;, latitude &lt;dbl&gt;, longitude &lt;dbl&gt;,
#   road_description &lt;chr&gt;, slope_description &lt;chr&gt;, dayofweek &lt;ord&gt;,
#   month &lt;ord&gt;, season &lt;chr&gt;</code></pre>
</div>
</div>
<p>The message above confirms that there are no duplicated records in thaiAccRaw, which is great!</p>
</section>
<section id="creating-simple-feature-data-frame" class="level4">
<h4 class="anchored" data-anchor-id="creating-simple-feature-data-frame">4.1.6 Creating Simple Feature Data Frame</h4>
<p>Next, the code chunk below helps to convert thaiAccRaw into a simple feature data frame by using st_as_sf() of sf packages.</p>
<p>As mentioned previously, the projected coordinate system of Thailand is WGS84/UTM zone 47N, and the EPSG code is 32647. Hence, we will set the following arguments accordingly: - coords argument to specify the column names to use for x- and y-coordinates - crs argument to specify the coordinates system in epsg format, EPSG:4326 for wgs84 and EPSG:32647 for Thailand’s projected coordinate system</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(thaiAccRaw, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(thaiAccSF, <span class="st">"data/rds/thaiAccSF.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved thaiAccSF.rds into R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/thaiAccSF.rds"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thaiAccSF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 12,986
Columns: 17
$ acc_code                    &lt;dbl&gt; 571882, 600001, 605043, 629691, 571887, 59…
$ incident_datetime           &lt;dttm&gt; 2019-01-01 02:25:00, 2019-01-01 03:00:00,…
$ province                    &lt;chr&gt; "Nakhon Pathom", "Nonthaburi", "Samut Prak…
$ agency                      &lt;chr&gt; "department of rural roads", "department o…
$ vehicle_type                &lt;chr&gt; "motorcycle", "private/passenger car", "pr…
$ presumed_cause              &lt;chr&gt; "speeding", "speeding", "running red light…
$ accident_type               &lt;chr&gt; "rollover/fallen on straight road", "rollo…
$ number_of_vehicles_involved &lt;dbl&gt; 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 2, …
$ number_of_fatalities        &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, …
$ number_of_injuries          &lt;dbl&gt; 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, …
$ weather_condition           &lt;chr&gt; "clear", "clear", "clear", "clear", "clear…
$ road_description            &lt;chr&gt; "straight road", "straight road", "other",…
$ slope_description           &lt;chr&gt; "no slope", "no slope", "other", "other", …
$ dayofweek                   &lt;ord&gt; Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tu…
$ month                       &lt;ord&gt; Jan, Jan, Jan, Jan, Jan, Jan, Jan, Jan, Ja…
$ season                      &lt;chr&gt; "Winter", "Winter", "Winter", "Winter", "W…
$ geometry                    &lt;POINT [m]&gt; POINT (627012.3 1533381), POINT (655…</code></pre>
</div>
</div>
<p>Note that a new column called geometry has been added into the data frame. Also, the columns longitude and latitude have been dropped from the data frame.</p>
</section>
</section>
<section id="geospatial-data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="geospatial-data-wrangling">4.2 Geospatial Data Wrangling</h3>
<section id="removing-columns-1" class="level4">
<h4 class="anchored" data-anchor-id="removing-columns-1">4.2.1 Removing Columns</h4>
<p>For thaiRoadsRaw data frame, we will be removing columns which do not contain values in English. We will also be removing columns which might not be helpful for our analysis - source, osm_id &amp; osm_type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>thaiRoadsRaw <span class="ot">&lt;-</span> thaiRoadsRaw <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">15</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thaiRoadsRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,792,590
Columns: 10
$ road       &lt;chr&gt; "Chalong Krung Road", "Soi Chalong Krung 1/1", NA, NA, "Cha…
$ highway    &lt;chr&gt; "secondary", "residential", "secondary_link", "service", "s…
$ surface    &lt;chr&gt; "paved", NA, NA, NA, "concrete", NA, NA, "unpaved", NA, NA,…
$ smoothness &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ width      &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ lanes      &lt;chr&gt; NA, NA, NA, NA, "2", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ oneway     &lt;chr&gt; "yes", NA, "yes", NA, "yes", NA, NA, NA, NA, NA, NA, NA, NA…
$ bridge     &lt;chr&gt; NA, NA, NA, NA, "yes", NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ layer      &lt;chr&gt; NA, NA, NA, NA, "1", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ geometry   &lt;MULTILINESTRING&gt; MULTILINESTRING ((100.7913 ..., MULTILINESTRING…</code></pre>
</div>
</div>
<p>thaiRoadsRaw now only consists of 10 columns, reduced from the original 15 columns.</p>
<p>Likewise, for the admBndpRaw data frame, we will be removing columns which do not contain values in English. We will also be removing columns which might not be helpful for our analysis, keeping only the key variables (province, which is ADM1_EN &amp; geometry) we want to use for our analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>admBndpRaw <span class="ot">&lt;-</span> admBndpRaw <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="dv">17</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(admBndpRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 77
Columns: 4
$ Shape_Leng &lt;dbl&gt; 2.417227, 1.695100, 1.251111, 1.884945, 3.041716, 1.739908,…
$ Shape_Area &lt;dbl&gt; 0.13133873, 0.07926199, 0.05323766, 0.12698345, 0.21393797,…
$ province   &lt;chr&gt; "Bangkok", "Samut Prakan", "Nonthaburi", "Pathum Thani", "P…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((100.6139 13..., MULTIPOLYGON (…</code></pre>
</div>
</div>
<p>admBndpRaw now only consists of 4 columns, reduced from the original 17 columns.</p>
</section>
<section id="filter-by-province-1" class="level4">
<h4 class="anchored" data-anchor-id="filter-by-province-1">4.2.2 Filter by Province</h4>
<p>We want to only focus on the study area (BMR) in our analysis. Hence, we will filter the province field to focus on the 6 provinces which are in the BMR: Bangkok, Nakhon Pathom, Pathum Thani, Nonthaburi, Samut Prakan and Samut Sakhon.</p>
<p>We will store these province names in a list and use it in our filter condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>bmr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Nakhon Pathom"</span>, <span class="st">"Pathum Thani"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Samut Prakan"</span>, <span class="st">"Samut Sakhon"</span>, <span class="st">"Bangkok"</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>admBndpRaw <span class="ot">&lt;-</span> admBndpRaw <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province <span class="sc">%in%</span> bmr)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(admBndpRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6
Columns: 4
$ Shape_Leng &lt;dbl&gt; 2.417227, 1.695100, 1.251111, 1.884945, 2.463030, 1.566369
$ Shape_Area &lt;dbl&gt; 0.13133873, 0.07926199, 0.05323766, 0.12698345, 0.17891420,…
$ province   &lt;chr&gt; "Bangkok", "Samut Prakan", "Nonthaburi", "Pathum Thani", "N…
$ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((100.6139 13..., MULTIPOLYGON (((100.7306 13…</code></pre>
</div>
</div>
<p>Note that after the filter is applied, admBndpRaw has been reduced to having only 6 rows, compared to the original 77 rows. Each of these 6 rows now represent each of the province in Bangkok Metropolitan Region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>tmap mode set to plotting</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(admBndpRaw, <span class="at">fill =</span> <span class="st">"province"</span>) <span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_legend</span>(<span class="at">main.title =</span> <span class="st">"Bangkok Metropolitan Region"</span>, <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"left"</span>, <span class="st">"top"</span>), <span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="filter-by-highway" class="level4">
<h4 class="anchored" data-anchor-id="filter-by-highway">4.2.3 Filter by Highway</h4>
<p>Taking reference from the below link, we will filter the highway field of thaiRoadsRaw to focus on the 5 key highway variables: motorway, primary, secondary, tertiary and unclassified.</p>
<p>Link: <a href="https://wiki.openstreetmap.org/wiki/WikiProject_Thailand#Highway_classification" class="uri">https://wiki.openstreetmap.org/wiki/WikiProject_Thailand#Highway_classification</a></p>
<p>We will store these highway values in a list and use it in our filter condition.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>highways <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"motorway"</span>, <span class="st">"primary"</span>, <span class="st">"secondary"</span>, <span class="st">"tertiary"</span>, <span class="st">"unclassified"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>thaiRoadsRaw <span class="ot">&lt;-</span> thaiRoadsRaw <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(highway <span class="sc">%in%</span> highways)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thaiRoadsRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 188,596
Columns: 10
$ road       &lt;chr&gt; "Chalong Krung Road", "Chalong Krung Road", "Erawan 1 Road"…
$ highway    &lt;chr&gt; "secondary", "secondary", "tertiary", "tertiary", "unclassi…
$ surface    &lt;chr&gt; "paved", "concrete", NA, NA, "gravel", "gravel", "gravel", …
$ smoothness &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ width      &lt;chr&gt; NA, NA, NA, NA, NA, NA, "4", NA, NA, NA, NA, NA, NA, NA, NA…
$ lanes      &lt;chr&gt; NA, "2", NA, NA, "1", "1", "1", "3", NA, NA, NA, NA, NA, "1…
$ oneway     &lt;chr&gt; "yes", "yes", NA, NA, NA, NA, NA, "yes", "yes", "yes", NA, …
$ bridge     &lt;chr&gt; NA, "yes", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "yes…
$ layer      &lt;chr&gt; NA, "1", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "1", N…
$ geometry   &lt;MULTILINESTRING&gt; MULTILINESTRING ((100.7913 ..., MULTILINESTRING…</code></pre>
</div>
</div>
<p>Note that after the filter is applied, thaiRoadsRaw has been reduced to having only 188,596 rows, compared to the original 2,792,590 rows.</p>
</section>
<section id="handling-multilinestring" class="level4">
<h4 class="anchored" data-anchor-id="handling-multilinestring">4.2.4 Handling Multilinestring</h4>
<p>For our spatio-temporal analysis, we require the geometry field in thaiRoadsRaw to be of LINESTRING instead of MULTILINESTRING.</p>
<p>To do this, we will utilize the st_cast() function from sf package to convert geometry field from MULTILINESTRING to LINESTRING.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>thaiRoadsRaw<span class="sc">$</span>geometry <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(thaiRoadsRaw<span class="sc">$</span>geometry, <span class="st">"LINESTRING"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thaiRoadsRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 188,596
Columns: 10
$ road       &lt;chr&gt; "Chalong Krung Road", "Chalong Krung Road", "Erawan 1 Road"…
$ highway    &lt;chr&gt; "secondary", "secondary", "tertiary", "tertiary", "unclassi…
$ surface    &lt;chr&gt; "paved", "concrete", NA, NA, "gravel", "gravel", "gravel", …
$ smoothness &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ width      &lt;chr&gt; NA, NA, NA, NA, NA, NA, "4", NA, NA, NA, NA, NA, NA, NA, NA…
$ lanes      &lt;chr&gt; NA, "2", NA, NA, "1", "1", "1", "3", NA, NA, NA, NA, NA, "1…
$ oneway     &lt;chr&gt; "yes", "yes", NA, NA, NA, NA, NA, "yes", "yes", "yes", NA, …
$ bridge     &lt;chr&gt; NA, "yes", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "yes…
$ layer      &lt;chr&gt; NA, "1", NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "1", N…
$ geometry   &lt;LINESTRING&gt; LINESTRING (100.7913 13.740..., LINESTRING (100.7831…</code></pre>
</div>
</div>
<p>Note that the geometry field in thaiRoadsRaw has been updated to LINESTRING now.</p>
</section>
<section id="coordinate-systems" class="level4">
<h4 class="anchored" data-anchor-id="coordinate-systems">4.2.5 Coordinate Systems</h4>
<p>As mentioned previously, the projected coordinate system of Thailand is WGS84/UTM zone 47N, and the EPSG code is 32647.</p>
<p>We can use st_crs() of sf package to identify the coordinate system of thaiRoadsRaw.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thaiRoadsRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System: NA</code></pre>
</div>
</div>
<p>The message above shows that there is no assignment of coordinate system for thaiRoadsRaw simple feature data frame. Hence, we will use the below code chunk to assign the CRS first before transforming the CRS to EPSG 32647.</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>thaiRoadsRaw <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(thaiRoadsRaw, <span class="dv">4326</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>thaiRoadsSF <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(thaiRoadsRaw, <span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(thaiRoadsSF, <span class="st">"data/rds/thaiRoadsSF.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved thaiRoadsSF.rds into R environment. Let us display the content of thaiRoadsSF to verify the updated CRS info.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>thaiRoadsSF <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/thaiRoadsSF.rds"</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thaiRoadsSF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32647 
  wkt:
PROJCRS["WGS 84 / UTM zone 47N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 47N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",99,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Between 96°E and 102°E, northern hemisphere between equator and 84°N, onshore and offshore. China. Indonesia. Laos. Malaysia - West Malaysia. Mongolia. Myanmar (Burma). Russian Federation. Thailand."],
        BBOX[0,96,84,102]],
    ID["EPSG",32647]]</code></pre>
</div>
</div>
<p>Likewise, we can use st_crs() of sf package to identify the coordinate system of admBndpRaw.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(admBndpRaw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>As the admBndpRaw simple feature data frame is in wgs84 coordinate system, we will perform projection transformation using the code chunk below.</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>admBndpRaw <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(admBndpRaw, <span class="dv">4326</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>admBndpSF <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(admBndpRaw, <span class="at">crs =</span> <span class="dv">32647</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(admBndpSF, <span class="st">"data/rds/admBndpSF.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved admBndpSF.rds into R environment. Let us display the content of admBndpSF to verify the updated CRS info.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>admBndpSF <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/admBndpSF.rds"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(admBndpSF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32647 
  wkt:
PROJCRS["WGS 84 / UTM zone 47N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 47N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",99,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Between 96°E and 102°E, northern hemisphere between equator and 84°N, onshore and offshore. China. Indonesia. Laos. Malaysia - West Malaysia. Mongolia. Myanmar (Burma). Russian Federation. Thailand."],
        BBOX[0,96,84,102]],
    ID["EPSG",32647]]</code></pre>
</div>
</div>
<p>Lastly, we can use st_crs() of sf package to identify the coordinate system of thaiAccSF.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thaiAccSF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:32647 
  wkt:
PROJCRS["WGS 84 / UTM zone 47N",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 47N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",99,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Between 96°E and 102°E, northern hemisphere between equator and 84°N, onshore and offshore. China. Indonesia. Laos. Malaysia - West Malaysia. Mongolia. Myanmar (Burma). Russian Federation. Thailand."],
        BBOX[0,96,84,102]],
    ID["EPSG",32647]]</code></pre>
</div>
</div>
<p>We have now verified that all our sf data frames contain the correct CRS information.</p>
</section>
<section id="intersection-of-data" class="level4">
<h4 class="anchored" data-anchor-id="intersection-of-data">4.2.6 Intersection of Data</h4>
<p>Our thaiRoadsSF data could contain information on roads which are out of the admin boundaries of the 6 provinces that we want to focus on. Hence, we will clip the data by performing an intersection of thaiRoadsSF with admBndpSF data using the code chunk below.</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>thaiRoadsBndSF <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thaiRoadsSF, admBndpSF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: attribute variables are assumed to be spatially constant throughout
all geometries</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(thaiRoadsBndSF, <span class="st">"data/rds/thaiRoadsBndSF.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved thaiRoadsBndSF.rds into R environment. We can use st_geometry() to visualize the intersection of data to ensure it worked correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>thaiRoadsBndSF <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/thaiRoadsBndSF.rds"</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(thaiRoadsBndSF))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can now proceed to tackle the objectives of this exercise.</p>
</section>
</section>
</section>
<section id="visualizing-spatio-temporal-dynamics-of-accidents" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-spatio-temporal-dynamics-of-accidents">5. Visualizing Spatio-Temporal Dynamics of Accidents</h2>
<p>The code chunk below helps us identify that out of the 6 provinces in BMR, Bangkok has the most number of accidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(province) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numAccidents =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> province, <span class="at">y =</span> numAccidents, <span class="at">fill =</span> province)) <span class="sc">+</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Province"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>, <span class="at">title =</span> <span class="st">"Number of Accidents by Province"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The code chunk below helps us identify that most of the accidents occurred when there were no slopes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(slope_description) <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numAccidents =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> slope_description, <span class="at">y =</span> numAccidents, <span class="at">fill =</span> slope_description)) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Slope Description"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>, <span class="at">title =</span> <span class="st">"Number of Accidents by Slope Description"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The code chunk below helps us identify that December was the month with the highest number of accidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(month) <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numAccidents =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> numAccidents, <span class="at">fill =</span> month)) <span class="sc">+</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Month"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>, <span class="at">title =</span> <span class="st">"Number of Accidents by Month"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The code chunk below helps us identify that more accidents occur on both Friday and Saturday.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dayofweek) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numAccidents =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> dayofweek, <span class="at">y =</span> numAccidents, <span class="at">fill =</span> dayofweek)) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day of Week"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>, <span class="at">title =</span> <span class="st">"Number of Accidents by Day of Week"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The code chunk below helps us identify that the number of accidents occurring each season are around the same.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(season) <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numAccidents =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> season, <span class="at">y =</span> numAccidents, <span class="at">fill =</span> season)) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Season"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>, <span class="at">title =</span> <span class="st">"Number of Accidents by Season"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also plot a heatmap to show the intensity of accidents over different days and times.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>thaiAccSF<span class="sc">$</span>hour <span class="ot">&lt;-</span> <span class="fu">format</span>(thaiAccSF<span class="sc">$</span>incident_datetime, <span class="st">"%H"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>thaiAccSF <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dayofweek, hour) <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numAccidents =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> hour, <span class="at">y =</span> dayofweek, <span class="at">fill =</span> numAccidents)) <span class="sc">+</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightyellow"</span>, <span class="at">high =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Accident Density by Hour and Day of Week"</span>, <span class="at">x =</span> <span class="st">"Hour of Day"</span>, <span class="at">y =</span> <span class="st">"Day of Week"</span>) <span class="sc">+</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'dayofweek'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s set the tmap_mode to plotting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tmap_mode("view")</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>tmap mode set to plotting</code></pre>
</div>
</div>
<p>We will create a map to show the location of accidents, with the admin boundaries and roads for context. We will be overlaying the thaiAccSF data as points on this map as dots.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(admBndpSF) <span class="sc">+</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightgray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(thaiAccSF) <span class="sc">+</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"province"</span>, <span class="at">size =</span> <span class="fl">0.02</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">title =</span> <span class="st">"Accident Locations in Bangkok Metropolitan Region"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next, we can break down the accident data over time using facets. This will help us analyse the accidents over time across the 6 provinces in BMR.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(admBndpSF) <span class="sc">+</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightgray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span> </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(thaiAccSF) <span class="sc">+</span> </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"month"</span>, <span class="at">size =</span> <span class="fl">0.02</span>) <span class="sc">+</span> </span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets</span>(<span class="at">by =</span> <span class="st">"province"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Likewise, we can break down the accident data over day of week using facets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(admBndpSF) <span class="sc">+</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightgray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(thaiAccSF) <span class="sc">+</span> </span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"dayofweek"</span>, <span class="at">size =</span> <span class="fl">0.02</span>) <span class="sc">+</span> </span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets</span>(<span class="at">by =</span> <span class="st">"province"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next, we can break down the accident data over seasons using facets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(admBndpSF) <span class="sc">+</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightgray"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span> </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(thaiAccSF) <span class="sc">+</span> </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"season"</span>, <span class="at">size =</span> <span class="fl">0.02</span>) <span class="sc">+</span> </span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets</span>(<span class="at">by =</span> <span class="st">"province"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex1D_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="spatial-analysis-using-network-spatial-point-patterns-analysis" class="level2">
<h2 class="anchored" data-anchor-id="spatial-analysis-using-network-spatial-point-patterns-analysis">6. Spatial Analysis using Network Spatial Point Patterns Analysis</h2>
<p>We will first use as_Spatial() of sf package to convert the three geospatial data from simple feature data frame to sp’s Spatial class.</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(thaiRoadsBndSF)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>boundary <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(admBndpSF)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>accidents <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(thaiAccSF)</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(roads, <span class="st">"data/rds/roads.rds"</span>)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(boundary, <span class="st">"data/rds/boundary.rds"</span>)</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(accidents, <span class="st">"data/rds/accidents.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved rds into R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/roads.rds"</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>boundary <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/boundary.rds"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>accidents <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/accidents.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will use the list() function to display the information of these spatial classes as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(roads)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
class       : SpatialLinesDataFrame 
features    : 24783 
extent      : 590124.8, 712235, 1484506, 1579041  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs 
variables   : 12
names       :            road,      highway, surface,   smoothness, width, lanes, oneway,  bridge, layer,    Shape_Leng,      Shape_Area,     province 
min values  : 25 Mokkara Road,     motorway, asphalt,          bad,    10,     0,     -1, movable,    -1, 1.25111117749, 0.0532376597241,      Bangkok 
max values  :     Yuwittaya 7, unclassified,    wood, intermediate,     9,     9,    yes,     yes,     4, 2.46303035967,  0.178914199749, Samut Sakhon </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(boundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
class       : SpatialPolygonsDataFrame 
features    : 6 
extent      : 587893.5, 712440.5, 1484414, 1579076  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs 
variables   : 3
names       :    Shape_Leng,      Shape_Area,     province 
min values  : 1.25111117749, 0.0532376597241,      Bangkok 
max values  : 2.46303035967,  0.178914199749, Samut Sakhon </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(accidents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
class       : SpatialPointsDataFrame 
features    : 12986 
extent      : 591277.5, 710166.1, 1486846, 1576520  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs 
variables   : 17
names       : acc_code, incident_datetime,     province,                           agency,         vehicle_type,        presumed_cause,                    accident_type, number_of_vehicles_involved, number_of_fatalities, number_of_injuries, weather_condition,           road_description, slope_description, dayofweek, month, ... 
min values  :   571882,        1546309500,      Bangkok,           department of highways, 4-wheel pickup truck,    abrupt lane change, collision at intersection corner,                           0,                    0,                  0,             clear, connecting to private area,          no slope,       Fri,   Apr, ... 
max values  :  7570954,        1672528260, Samut Sakhon, expressway authority of thailand,                  van, worn-out/tire blowout,     turning/retreating collision,                          12,                   13,                 51,             rainy,             y-intersection,        slope area,       Wed,   Sep, ... </code></pre>
</div>
</div>
<p>spatstat requires the data in ppp object form. Before that, we will convert these spatial classes into generic sp format first.</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>accidentsSP <span class="ot">&lt;-</span> <span class="fu">as</span>(accidents, <span class="st">"SpatialPoints"</span>)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>boundarySP <span class="ot">&lt;-</span> <span class="fu">as</span>(boundary, <span class="st">"SpatialPolygons"</span>)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(accidentsSP, <span class="st">"data/rds/accidentsSP.rds"</span>)</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(boundarySP, <span class="st">"data/rds/boundarySP.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved rds into R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>accidentsSP <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/accidentsSP.rds"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>boundarySP <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/boundarySP.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Likewise, will use the list() function to display the information of these spatial objects as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(accidentsSP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
class       : SpatialPoints 
features    : 12986 
extent      : 591277.5, 710166.1, 1486846, 1576520  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list</span>(boundarySP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
class       : SpatialPolygons 
features    : 6 
extent      : 587893.5, 712440.5, 1484414, 1579076  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs </code></pre>
</div>
</div>
<p>Now, we will use the as.ppp() function of spatstat to convert the spatial data into spatstat’s ppp object format.</p>
<p>The output will be saved in rds format for future use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># facing issues with installing/loading spatstat &amp; spatstat.data</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="co"># accidentsPPP &lt;- spatstat::as.ppp(accidentsSP)</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="co"># write_rds(accidentsPPP, "data/rds/accidentsPPP.rds")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code chunk below will be used to import the saved rds into R environment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># accidentsPPP &lt;- read_rds("data/rds/accidentsPPP.rds")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="spatio-temporal-analysis-using-temporal-network-spatial-point-patterns-analysis" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-analysis-using-temporal-network-spatial-point-patterns-analysis">7. Spatio-Temporal Analysis using Temporal Network Spatial Point Patterns Analysis</h2>
<p>We will be performing network kernel density estimation by using the appropriate functions provided in spNetwork package.</p>
<p>Before computing NKDE, we need to cut the linestring object into lixels with a specified minimal distance. We will be using lixelize_lines() of spNetwork package for this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="co">#thaiRoadsBndSF$geometry &lt;- st_cast(thaiRoadsBndSF$geometry, "LINESTRING")</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="co">#lixels &lt;- lixelize_lines(thaiRoadsBndSF, 700, mindist = 375)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, we will use lines_center() of spNetwork package to generate a SpatialPointsDataFrame with line centre points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co">#samples &lt;- lines_center(lixels)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This would mean that the points are located at center of the lines based on the length of the line.</p>
<p>We can now compute NKDE by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="co">#densities &lt;- nkde(thaiRoadsBndSF, </span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="co">#                  events = thaiAccSF,</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="co">#                  w = rep(1, nrow(thaiAccSF)),</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a><span class="co">#                  samples = samples,</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="co">#                  kernel_name = "quartic",</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a><span class="co">#                  bw = 300, </span></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="co">#                  div= "bw", </span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a><span class="co">#                  method = "simple", </span></span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a><span class="co">#                  digits = 1, </span></span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a><span class="co">#                  tol = 1,</span></span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a><span class="co">#                  grid_shape = c(1,1), </span></span>
<span id="cb93-13"><a href="#cb93-13" aria-hidden="true" tabindex="-1"></a><span class="co">#                  max_depth = 8,</span></span>
<span id="cb93-14"><a href="#cb93-14" aria-hidden="true" tabindex="-1"></a><span class="co">#                  agg = 5, </span></span>
<span id="cb93-15"><a href="#cb93-15" aria-hidden="true" tabindex="-1"></a><span class="co">#                  sparse = TRUE,</span></span>
<span id="cb93-16"><a href="#cb93-16" aria-hidden="true" tabindex="-1"></a><span class="co">#                  verbose = FALSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before we visualize NKDE values, we will use the code chunk below to insert the computed density values into samples, and the lixels objects as density.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="co">#samples$density &lt;- densities</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="co">#lixels$density &lt;- densities</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now prepare the following map visualization.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co">#tmap_mode('plot')</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(lixels)+</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  tm_lines(col="density")+</span></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(thaiAccSF)+</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  tm_dots()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>xx…</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>